/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiAuditsGetAPIAudits } from "../../funcs/apiAuditsGetAPIAudits.js";
import { GetApiAuditsRequest$zodSchema } from "../../models/getapiauditsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiAuditsRequest$zodSchema,
};

export const tool$apiAuditsGetAPIAudits: ToolDefinition<typeof args> = {
  name: "get_api_audits",
  description: `Get API Audit

Get API Audit.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Audits",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiAuditsGetAPIAudits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
