/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiAnalyticsGetAPILogs } from "../../funcs/apiAnalyticsGetAPILogs.js";
import { GetApiLogsRequest$zodSchema } from "../../models/getapilogsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiLogsRequest$zodSchema,
};

export const tool$apiAnalyticsGetAPILogs: ToolDefinition<typeof args> = {
  name: "API-analytics-get-api-logs",
  description: `Get API logs

Get API logs.

User must have the API_LOG[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiAnalyticsGetAPILogs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
