/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiAnalyticsGetResponseStatusCodes } from "../../funcs/apiAnalyticsGetResponseStatusCodes.js";
import { GetResponseStatusCodesRequest$zodSchema } from "../../models/getresponsestatuscodesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetResponseStatusCodesRequest$zodSchema,
};

export const tool$apiAnalyticsGetResponseStatusCodes: ToolDefinition<
  typeof args
> = {
  name: "API-analytics-get-response-status-codes",
  description: `Get API Analytics response status counts

Get API analytics response status counts. Response statuses are grouped by endpoint and status code hundreds.

User must have the API_ANALYTICS[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiAnalyticsGetResponseStatusCodes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
