/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiAuditsListAPIAuditEvents } from "../../funcs/apiAuditsListAPIAuditEvents.js";
import { ListApiAuditEventsRequest$zodSchema } from "../../models/listapiauditeventsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListApiAuditEventsRequest$zodSchema,
};

export const tool$apiAuditsListAPIAuditEvents: ToolDefinition<typeof args> = {
  name: "API-audits-list-api-audit-events",
  description: `List available audit event type for API

List available audit event type for API.

User must have the API_AUDIT[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiAuditsListAPIAuditEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
