/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocumentationGetAPIPage } from "../../funcs/apiDocumentationGetAPIPage.js";
import { GetApiPageRequest$zodSchema } from "../../models/getapipageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiPageRequest$zodSchema,
};

export const tool$apiDocumentationGetAPIPage: ToolDefinition<typeof args> = {
  name: "API-documentation-get-api-page",
  description: `Get API Documentation Page

Get API Documentation Page by ID.

User must have the API_DOCUMENTATION[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocumentationGetAPIPage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
