/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocumentationUnpublishDocumentationPage } from "../../funcs/apiDocumentationUnpublishDocumentationPage.js";
import { UnpublishDocumentationPageRequest$zodSchema } from "../../models/unpublishdocumentationpageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UnpublishDocumentationPageRequest$zodSchema,
};

export const tool$apiDocumentationUnpublishDocumentationPage: ToolDefinition<
  typeof args
> = {
  name: "API-documentation-unpublish-documentation-page",
  description: `Unpublish API Documentation Page

Unpublish API Documentation Page. Returns the unpublished page.

User must have the API_DOCUMENTATION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocumentationUnpublishDocumentationPage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
