/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiEventsGetAPIEventById } from "../../funcs/apiEventsGetAPIEventById.js";
import { GetApiEventByIdRequest$zodSchema } from "../../models/getapieventbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiEventByIdRequest$zodSchema,
};

export const tool$apiEventsGetAPIEventById: ToolDefinition<typeof args> = {
  name: "API-events-get-api-event-by-id",
  description: `Get single API Event by it's ID

Get specific single API Event.

User must have the API_EVENT[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiEventsGetAPIEventById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
