/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiEventsGetAPIEventById } from "../../funcs/apiEventsGetAPIEventById.js";
import { GetApiEventByIdRequest$zodSchema } from "../../models/getapieventbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiEventByIdRequest$zodSchema,
};

export const tool$apiEventsGetAPIEventById: ToolDefinition<typeof args> = {
  name: "get_api_event_by_id",
  description: `Get single API Event by it's ID

Get specific single API Event.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Event By Id",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiEventsGetAPIEventById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
