/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiEventsGetAPIEvents } from "../../funcs/apiEventsGetAPIEvents.js";
import { GetApiEventsRequest$zodSchema } from "../../models/getapieventsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiEventsRequest$zodSchema,
};

export const tool$apiEventsGetAPIEvents: ToolDefinition<typeof args> = {
  name: "get_api_events",
  description: `Get API Events

Get API Events.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Events",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiEventsGetAPIEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
