/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiHealthGetAPIHealthLogs } from "../../funcs/apiHealthGetAPIHealthLogs.js";
import { GetApiHealthLogsRequest$zodSchema } from "../../models/getapihealthlogsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiHealthLogsRequest$zodSchema,
};

export const tool$apiHealthGetAPIHealthLogs: ToolDefinition<typeof args> = {
  name: "get_api_health_logs",
  description: `Get API Health Check logs

Get API Health Check average response time overtime.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Health Logs",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiHealthGetAPIHealthLogs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
