/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiHealthGetAPIHealthAverageResponseTime } from "../../funcs/apiHealthGetAPIHealthAverageResponseTime.js";
import { GetApiHealthAverageResponseTimeRequest$zodSchema } from "../../models/getapihealthaverageresponsetimeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiHealthAverageResponseTimeRequest$zodSchema,
};

export const tool$apiHealthGetAPIHealthAverageResponseTime: ToolDefinition<
  typeof args
> = {
  name: "get_api_health_average_response_time",
  description: `Get API Health Check average response time

Get API Health Check average response time.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Health Average Response Time",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiHealthGetAPIHealthAverageResponseTime(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
