/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiHealthGetAPIHealthAverageResponseTimeOvertime } from "../../funcs/apiHealthGetAPIHealthAverageResponseTimeOvertime.js";
import { GetApiHealthAverageResponseTimeOvertimeRequest$zodSchema } from "../../models/getapihealthaverageresponsetimeovertimeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiHealthAverageResponseTimeOvertimeRequest$zodSchema,
};

export const tool$apiHealthGetAPIHealthAverageResponseTimeOvertime:
  ToolDefinition<typeof args> = {
    name: "get_api_health_average_response_time_overtime",
    description: `Get API Health Check average response time overtime

Get API Health Check average response time overtime.`,
    scopes: ["read"],
    annotations: {
      "title": "Get Api Health Average Response Time Overtime",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await apiHealthGetAPIHealthAverageResponseTimeOvertime(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
