/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiMembersAddAPIMember } from "../../funcs/apiMembersAddAPIMember.js";
import { AddApiMemberRequest$zodSchema } from "../../models/addapimemberop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddApiMemberRequest$zodSchema,
};

export const tool$apiMembersAddAPIMember: ToolDefinition<typeof args> = {
  name: "add_api_member",
  description: `Add a member to an API.

Add a new member to an API. Returns a 400 HTTP Error:`,
  scopes: ["write"],
  annotations: {
    "title": "Add Api Member",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiMembersAddAPIMember(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
