/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiMembersListAPIMembers } from "../../funcs/apiMembersListAPIMembers.js";
import { ListApiMembersRequest$zodSchema } from "../../models/listapimembersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListApiMembersRequest$zodSchema,
};

export const tool$apiMembersListAPIMembers: ToolDefinition<typeof args> = {
  name: "API-members-list-api-members",
  description: `Get the API's members

List the members for a given API.

User must have the API_MEMBER[READ] permission.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiMembersListAPIMembers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
