/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiProductGetAPIProductsForAPI } from "../../funcs/apiProductGetAPIProductsForAPI.js";
import { GetApiProductsForApiRequest$zodSchema } from "../../models/getapiproductsforapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiProductsForApiRequest$zodSchema,
};

export const tool$apiProductGetAPIProductsForAPI: ToolDefinition<typeof args> =
  {
    name: "get_api_products_for_api",
    description: `Get API Products for an API

Returns the list of API Products that include the specified API.`,
    scopes: ["read"],
    annotations: {
      "title": "Get Api Products For Api",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await apiProductGetAPIProductsForAPI(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
