/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiPlansPublishAPIPlan } from "../../funcs/apiPlansPublishAPIPlan.js";
import { PublishApiPlanRequest$zodSchema } from "../../models/publishapiplanop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PublishApiPlanRequest$zodSchema,
};

export const tool$apiPlansPublishAPIPlan: ToolDefinition<typeof args> = {
  name: "API-plans-publish-api-plan",
  description: `Publish an API's plan

Publish the API's plan.

User must have the API_PLAN[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiPlansPublishAPIPlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
