/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiPlansListAPIPlans } from "../../funcs/apiPlansListAPIPlans.js";
import { ListApiPlansRequest$zodSchema } from "../../models/listapiplansop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListApiPlansRequest$zodSchema,
};

export const tool$apiPlansListAPIPlans: ToolDefinition<typeof args> = {
  name: "list_api_plans",
  description: `List the API's plans

List plans for a given API, always filtered by a \`status\` and the possibility to filter by \`security\`.<br> The results are paginated.`,
  scopes: ["read"],
  annotations: {
    "title": "List Api Plans",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiPlansListAPIPlans(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
