/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsExportApiDefinition } from "../../funcs/apIsExportApiDefinition.js";
import { ExportApiDefinitionRequest$zodSchema } from "../../models/exportapidefinitionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExportApiDefinitionRequest$zodSchema,
};

export const tool$apIsExportApiDefinition: ToolDefinition<typeof args> = {
  name: "export_api_definition",
  description: `Export an API

⚠️ Support only v4 API for the moment. ⚠️ Export an API to a JSON file. User should also have these permissions for specific data: - API_DEFINITION[READ] for the API - API_MEMBER[READ] for the API's members - API_PLAN[READ] for the API's plans`,
  scopes: ["read"],
  annotations: {
    "title": "Export Api Definition",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsExportApiDefinition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
