/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsRejectAPISubscription } from "../../funcs/apiSubscriptionsRejectAPISubscription.js";
import { RejectApiSubscriptionRequest$zodSchema } from "../../models/rejectapisubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RejectApiSubscriptionRequest$zodSchema,
};

export const tool$apiSubscriptionsRejectAPISubscription: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-reject-api-subscription",
  description: `Reject an API subscription

Reject an API subscription with an optional reason.

User must have the API_SUBSCRIPTION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsRejectAPISubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
