/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsCreateApiDeployment } from "../../funcs/apIsCreateApiDeployment.js";
import { CreateApiDeploymentRequest$zodSchema } from "../../models/createapideploymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateApiDeploymentRequest$zodSchema,
};

export const tool$apIsCreateApiDeployment: ToolDefinition<typeof args> = {
  name: "AP-is-create-api-deployment",
  description: `Request a deployment to gateway instances

Request a deployment for a given API. <br>
An optional deployment label can be given to the requested deployment.

User must have the API_DEFINITION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsCreateApiDeployment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
