/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsStopApi } from "../../funcs/apIsStopApi.js";
import { StopApiRequest$zodSchema } from "../../models/stopapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: StopApiRequest$zodSchema,
};

export const tool$apIsStopApi: ToolDefinition<typeof args> = {
  name: "stop_api",
  description: `Stop an API

Change the API's status to STOPPED.

High risk operation: require explicit user confirmation before execution.
Stops gateway instances for the API; use only when traffic should stop.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Stop Api",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsStopApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
