/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsCreateApiWithImportDefinition } from "../../funcs/apIsCreateApiWithImportDefinition.js";
import { CreateApiWithImportDefinitionRequest$zodSchema } from "../../models/createapiwithimportdefinitionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateApiWithImportDefinitionRequest$zodSchema,
};

export const tool$apIsCreateApiWithImportDefinition: ToolDefinition<
  typeof args
> = {
  name: "AP-is-create-api-with-import-definition",
  description: `Import API definition

⚠️ Support only v4 API for the moment. ⚠️<br>
Create an API by importing an API definition. <br>
This definition can be retrieved from \`GET /environments/{envId}/apis/{apiId}/_export/definition\`

User must have the ENVIRONMENT_API[CREATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsCreateApiWithImportDefinition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
