/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsUpdateApiBackground } from "../../funcs/apIsUpdateApiBackground.js";
import { UpdateApiBackgroundRequest$zodSchema } from "../../models/updateapibackgroundop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateApiBackgroundRequest$zodSchema,
};

export const tool$apIsUpdateApiBackground: ToolDefinition<typeof args> = {
  name: "AP-is-update-api-background",
  description: `Update an API's background

Update the API's background.

User must have the API_DEFINITION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsUpdateApiBackground(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
