/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsTransferAPISubscription } from "../../funcs/apiSubscriptionsTransferAPISubscription.js";
import { TransferApiSubscriptionRequest$zodSchema } from "../../models/transferapisubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TransferApiSubscriptionRequest$zodSchema,
};

export const tool$apiSubscriptionsTransferAPISubscription: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-transfer-api-subscription",
  description: `Transfer an API subscription

Transfer an API subscription to another plan.<br>
The targeted plan must be published and must have the same security type. Transfer cannot be performed if general conditions apply to the targeted plan.

User must have the API_SUBSCRIPTION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsTransferAPISubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
