/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsReactivateAPISubscriptionAPIKey } from "../../funcs/apiSubscriptionsReactivateAPISubscriptionAPIKey.js";
import { ReactivateApiSubscriptionApiKeyRequest$zodSchema } from "../../models/reactivateapisubscriptionapikeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReactivateApiSubscriptionApiKeyRequest$zodSchema,
};

export const tool$apiSubscriptionsReactivateAPISubscriptionAPIKey:
  ToolDefinition<typeof args> = {
    name: "API-subscriptions-reactivate-api-subscription-api-key",
    description: `Reactivate subscription API Key

Reactivate the revoked or expired subscription API Key.

User must have the API_SUBSCRIPTION[UPDATE] permission.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await apiSubscriptionsReactivateAPISubscriptionAPIKey(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
