/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsGetAPISubscriptionAPIKeys } from "../../funcs/apiSubscriptionsGetAPISubscriptionAPIKeys.js";
import { GetApiSubscriptionApiKeysRequest$zodSchema } from "../../models/getapisubscriptionapikeysop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiSubscriptionApiKeysRequest$zodSchema,
};

export const tool$apiSubscriptionsGetAPISubscriptionAPIKeys: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-get-api-subscription-api-keys",
  description: `Get subscription's API Keys

Get the subscription API Keys.

User must have the API_SUBSCRIPTION[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsGetAPISubscriptionAPIKeys(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
