/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsGetApiMetadata } from "../../funcs/apIsGetApiMetadata.js";
import { GetApiMetadataRequest$zodSchema } from "../../models/getapimetadataop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiMetadataRequest$zodSchema,
};

export const tool$apIsGetApiMetadata: ToolDefinition<typeof args> = {
  name: "AP-is-get-api-metadata",
  description: `Get metadata pertaining to API

Get the metadata that pertains to an API. Can be global and API metadata.

User must have the API_METADATA[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsGetApiMetadata(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
