/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsPauseAPISubscription } from "../../funcs/apiSubscriptionsPauseAPISubscription.js";
import { PauseApiSubscriptionRequest$zodSchema } from "../../models/pauseapisubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PauseApiSubscriptionRequest$zodSchema,
};

export const tool$apiSubscriptionsPauseAPISubscription: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-pause-api-subscription",
  description: `Pause one API's subscription

Pause the API's subscription.

User must have the API_SUBSCRIPTION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsPauseAPISubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
