/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsGetAPISubscribers } from "../../funcs/apiSubscriptionsGetAPISubscribers.js";
import { GetApiSubscribersRequest$zodSchema } from "../../models/getapisubscribersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiSubscribersRequest$zodSchema,
};

export const tool$apiSubscriptionsGetAPISubscribers: ToolDefinition<
  typeof args
> = {
  name: "get_api_subscribers",
  description: `Get the API's subscribers

List applications that have subscribed to a given API.<br> The results are paginated.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Subscribers",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsGetAPISubscribers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
