/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsDeleteApi } from "../../funcs/apIsDeleteApi.js";
import { DeleteApiRequest$zodSchema } from "../../models/deleteapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteApiRequest$zodSchema,
};

export const tool$apIsDeleteApi: ToolDefinition<typeof args> = {
  name: "delete_api",
  description: `Delete an API

Delete a V2 or a V4 API.

High risk operation: require explicit user confirmation before execution.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Delete Api",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsDeleteApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
