/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSpecGenGetSpecGenState } from "../../funcs/apiSpecGenGetSpecGenState.js";
import { GetSpecGenStateRequest$zodSchema } from "../../models/getspecgenstateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSpecGenStateRequest$zodSchema,
};

export const tool$apiSpecGenGetSpecGenState: ToolDefinition<typeof args> = {
  name: "get_spec_gen_state",
  description: `Evaluate the state of the API SpecGen`,
  scopes: ["read"],
  annotations: {
    "title": "Get Spec Gen State",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSpecGenGetSpecGenState(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
