/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiScoringGetAPIScoring } from "../../funcs/apiScoringGetAPIScoring.js";
import { GetApiScoringRequest$zodSchema } from "../../models/getapiscoringop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiScoringRequest$zodSchema,
};

export const tool$apiScoringGetAPIScoring: ToolDefinition<typeof args> = {
  name: "get_api_scoring",
  description: `Get API Scoring

Get API Scoring. Return a 404 HTTP Response status if API was never evaluated.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Scoring",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiScoringGetAPIScoring(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
