/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsCreateApiFromWsdl } from "../../funcs/apIsCreateApiFromWsdl.js";
import { CreateApiFromWsdlRequest$zodSchema } from "../../models/createapifromwsdlop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateApiFromWsdlRequest$zodSchema,
};

export const tool$apIsCreateApiFromWsdl: ToolDefinition<typeof args> = {
  name: "create_api_from_wsdl",
  description: `Create API from WSDL

Create a v4 HTTP Proxy API from a WSDL descriptor. The WSDL is converted to OpenAPI and processed through the v4 OAI import pipeline. Payload can be inline WSDL (type: INLINE) or a remote URL (type: URL).`,
  scopes: ["write"],
  annotations: {
    "title": "Create Api From Wsdl",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsCreateApiFromWsdl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
