/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsReviewsAccept } from "../../funcs/apIsReviewsAccept.js";
import { ReviewsAcceptRequest$zodSchema } from "../../models/reviewsacceptop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReviewsAcceptRequest$zodSchema,
};

export const tool$apIsReviewsAccept: ToolDefinition<typeof args> = {
  name: "AP-is-reviews-accept",
  description: `Accept a review

Accept a review

Return a 400 HTTP Error:
 - when user tries to change reviews state of an ARCHIVED API
 - when user tries to change reviews state of an API that is not in review

User must have the API_REVIEWS[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsReviewsAccept(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
