/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsReviewsAsk } from "../../funcs/apIsReviewsAsk.js";
import { ReviewsAskRequest$zodSchema } from "../../models/reviewsaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReviewsAskRequest$zodSchema,
};

export const tool$apIsReviewsAsk: ToolDefinition<typeof args> = {
  name: "AP-is-reviews-ask",
  description: `Ask for a review

Ask for a review

Return a 400 HTTP Error:
 - when user tries to change reviews state of an ARCHIVED API
 - when user tries to change reviews state of an API already in review

User must have the API_DEFINITION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsReviewsAsk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
