/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsGetCurrentApiDeployment } from "../../funcs/apIsGetCurrentApiDeployment.js";
import { GetCurrentApiDeploymentRequest$zodSchema } from "../../models/getcurrentapideploymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCurrentApiDeploymentRequest$zodSchema,
};

export const tool$apIsGetCurrentApiDeployment: ToolDefinition<typeof args> = {
  name: "get_current_api_deployment",
  description: `Get the current deployment of an API

Get the current deployment of an API.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Current Api Deployment",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsGetCurrentApiDeployment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
