/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsAcceptAPISubscription } from "../../funcs/apiSubscriptionsAcceptAPISubscription.js";
import { AcceptApiSubscriptionRequest$zodSchema } from "../../models/acceptapisubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AcceptApiSubscriptionRequest$zodSchema,
};

export const tool$apiSubscriptionsAcceptAPISubscription: ToolDefinition<
  typeof args
> = {
  name: "accept_api_subscription",
  description: `Accept an API subscription

Accept an API subscription with an optional starting / ending dates and reason.`,
  scopes: ["write"],
  annotations: {
    "title": "Accept Api Subscription",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsAcceptAPISubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
