/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsCloseAPISubscription } from "../../funcs/apiSubscriptionsCloseAPISubscription.js";
import { CloseApiSubscriptionRequest$zodSchema } from "../../models/closeapisubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloseApiSubscriptionRequest$zodSchema,
};

export const tool$apiSubscriptionsCloseAPISubscription: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-close-api-subscription",
  description: `Close one API's subscription

Close the API's subscription.

User must have the API_SUBSCRIPTION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsCloseAPISubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
