/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsUpdateAPISubscriptionAPIKey } from "../../funcs/apiSubscriptionsUpdateAPISubscriptionAPIKey.js";
import { UpdateApiSubscriptionApiKeyRequest$zodSchema } from "../../models/updateapisubscriptionapikeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateApiSubscriptionApiKeyRequest$zodSchema,
};

export const tool$apiSubscriptionsUpdateAPISubscriptionAPIKey: ToolDefinition<
  typeof args
> = {
  name: "update_api_subscription_api_key",
  description: `Update a subscription API Key

Update the subscription API Key.`,
  scopes: ["write"],
  annotations: {
    "title": "Update Api Subscription Api Key",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsUpdateAPISubscriptionAPIKey(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
