/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsListApis } from "../../funcs/apIsListApis.js";
import { ListApisRequest$zodSchema } from "../../models/listapisop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListApisRequest$zodSchema,
};

export const tool$apIsListApis: ToolDefinition<typeof args> = {
  name: "list_apis",
  description: `List APIs

Get the list of APIs for a specific environment.<br> The results are paginated.`,
  scopes: ["read"],
  annotations: {
    "title": "List Apis",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsListApis(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
