/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsUpdateApiWithDefinition } from "../../funcs/apIsUpdateApiWithDefinition.js";
import { UpdateApiWithDefinitionRequest$zodSchema } from "../../models/updateapiwithdefinitionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateApiWithDefinitionRequest$zodSchema,
};

export const tool$apIsUpdateApiWithDefinition: ToolDefinition<typeof args> = {
  name: "update_api_with_definition",
  description: `Update API from definition

Update an existing API by importing a Gravitee API definition.<br> This definition can be retrieved from \`GET /environments/{envId}/apis/{apiId}/_export/definition\``,
  scopes: ["write"],
  annotations: {
    "title": "Update Api With Definition",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsUpdateApiWithDefinition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
