/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsRevokeAPISubscriptionAPIKey } from "../../funcs/apiSubscriptionsRevokeAPISubscriptionAPIKey.js";
import { RevokeApiSubscriptionApiKeyRequest$zodSchema } from "../../models/revokeapisubscriptionapikeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RevokeApiSubscriptionApiKeyRequest$zodSchema,
};

export const tool$apiSubscriptionsRevokeAPISubscriptionAPIKey: ToolDefinition<
  typeof args
> = {
  name: "revoke_api_subscription_api_key",
  description: `Revoke a subscription API Key

Revoke the subscription API Key by setting the revocation date to the current date and flagging it as revoked.<br> A notification will be sent to the subscriber according to his portal notification options.

High risk operation: require explicit user confirmation before execution.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Revoke Api Subscription Api Key",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsRevokeAPISubscriptionAPIKey(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
