/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsExportAPISubscriptions } from "../../funcs/apiSubscriptionsExportAPISubscriptions.js";
import { ExportApiSubscriptionsRequest$zodSchema } from "../../models/exportapisubscriptionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExportApiSubscriptionsRequest$zodSchema,
};

export const tool$apiSubscriptionsExportAPISubscriptions: ToolDefinition<
  typeof args
> = {
  name: "export_api_subscriptions",
  description: `Export API subscriptions as CSV

Export API subscriptions to a CSV file.`,
  scopes: ["read"],
  annotations: {
    "title": "Export Api Subscriptions",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsExportAPISubscriptions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
