/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsStartApi } from "../../funcs/apIsStartApi.js";
import { StartApiRequest$zodSchema } from "../../models/startapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: StartApiRequest$zodSchema,
};

export const tool$apIsStartApi: ToolDefinition<typeof args> = {
  name: "start_api",
  description: `Start an API

Change the API's status to STARTED.

Start only after the API has been deployed.`,
  scopes: ["write"],
  annotations: {
    "title": "Start Api",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsStartApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
