/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsExposedEntrypoints } from "../../funcs/apIsExposedEntrypoints.js";
import { ExposedEntrypointsRequest$zodSchema } from "../../models/exposedentrypointsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExposedEntrypointsRequest$zodSchema,
};

export const tool$apIsExposedEntrypoints: ToolDefinition<typeof args> = {
  name: "exposed_entrypoints",
  description: `Get Exposed API Entrypoints

Get the list of exposed API entry points. This list represents the API's usable entrypoints that can be used by a client. It takes into account tags associated with the API or configured AccessPoint.`,
  scopes: ["read"],
  annotations: {
    "title": "Exposed Entrypoints",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsExposedEntrypoints(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
