/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsUpdateApiWithDefinitionFromUrl } from "../../funcs/apIsUpdateApiWithDefinitionFromUrl.js";
import { UpdateApiWithDefinitionFromUrlRequest$zodSchema } from "../../models/updateapiwithdefinitionfromurlop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateApiWithDefinitionFromUrlRequest$zodSchema,
};

export const tool$apIsUpdateApiWithDefinitionFromUrl: ToolDefinition<
  typeof args
> = {
  name: "update_api_with_definition_from_url",
  description: `Update API from a definition fetched from a remote URL

⚠️ Support only v4 API for the moment. ⚠️<br> Update an existing API by fetching a Gravitee API definition from a remote URL.<br> The URL must be permitted by the configured import whitelist.`,
  scopes: ["write"],
  annotations: {
    "title": "Update Api With Definition From Url",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsUpdateApiWithDefinitionFromUrl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
