/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiScoringTriggerAPIScoring } from "../../funcs/apiScoringTriggerAPIScoring.js";
import { TriggerApiScoringRequest$zodSchema } from "../../models/triggerapiscoringop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TriggerApiScoringRequest$zodSchema,
};

export const tool$apiScoringTriggerAPIScoring: ToolDefinition<typeof args> = {
  name: "API-scoring-trigger-api-scoring",
  description: `Trigger API Scoring

Trigger API Scoring.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiScoringTriggerAPIScoring(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
