/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsDeleteApiPicture } from "../../funcs/apIsDeleteApiPicture.js";
import { DeleteApiPictureRequest$zodSchema } from "../../models/deleteapipictureop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteApiPictureRequest$zodSchema,
};

export const tool$apIsDeleteApiPicture: ToolDefinition<typeof args> = {
  name: "AP-is-delete-api-picture",
  description: `Delete an API's picture

Delete the API's picture.

User must have the API_DEFINITION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsDeleteApiPicture(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
