/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsMigrateApi } from "../../funcs/apIsMigrateApi.js";
import { MigrateApiRequest$zodSchema } from "../../models/migrateapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: MigrateApiRequest$zodSchema,
};

export const tool$apIsMigrateApi: ToolDefinition<typeof args> = {
  name: "migrate_api",
  description: `Migrate an API

⚠️ Experimental endpoints - subject to change Migrate an APIv2 to APIv4.

High risk operation: require explicit user confirmation before execution.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Migrate Api",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsMigrateApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
