/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsVerifyAPIDeployment } from "../../funcs/apiSubscriptionsVerifyAPIDeployment.js";
import { VerifyApiDeploymentRequest$zodSchema } from "../../models/verifyapideploymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VerifyApiDeploymentRequest$zodSchema,
};

export const tool$apiSubscriptionsVerifyAPIDeployment: ToolDefinition<
  typeof args
> = {
  name: "verify_api_deployment",
  description: `Check if a deployment is possible

Check if an API deployment is possible given the API's definition and license used by the organization.`,
  scopes: ["read"],
  annotations: {
    "title": "Verify Api Deployment",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsVerifyAPIDeployment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
