/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsGetAPISubscriptionAPIKeys } from "../../funcs/apiSubscriptionsGetAPISubscriptionAPIKeys.js";
import { GetApiSubscriptionApiKeysRequest$zodSchema } from "../../models/getapisubscriptionapikeysop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiSubscriptionApiKeysRequest$zodSchema,
};

export const tool$apiSubscriptionsGetAPISubscriptionAPIKeys: ToolDefinition<
  typeof args
> = {
  name: "get_api_subscription_api_keys",
  description: `Get subscription's API Keys

Get the subscription API Keys.`,
  scopes: ["read"],
  annotations: {
    "title": "Get Api Subscription Api Keys",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsGetAPISubscriptionAPIKeys(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
