/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apIsDeleteApiBackground } from "../../funcs/apIsDeleteApiBackground.js";
import { DeleteApiBackgroundRequest$zodSchema } from "../../models/deleteapibackgroundop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteApiBackgroundRequest$zodSchema,
};

export const tool$apIsDeleteApiBackground: ToolDefinition<typeof args> = {
  name: "AP-is-delete-api-background",
  description: `Delete an API's background

Delete the API's background.

User must have the API_DEFINITION[UPDATE] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apIsDeleteApiBackground(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
