/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiSubscriptionsGetAPISubscribers } from "../../funcs/apiSubscriptionsGetAPISubscribers.js";
import { GetApiSubscribersRequest$zodSchema } from "../../models/getapisubscribersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetApiSubscribersRequest$zodSchema,
};

export const tool$apiSubscriptionsGetAPISubscribers: ToolDefinition<
  typeof args
> = {
  name: "API-subscriptions-get-api-subscribers",
  description: `Get the API's subscribers

List applications that have subscribed to a given API.<br>
The results are paginated.

User must have API_SUBSCRIPTION[READ] permissions to access endpoint.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiSubscriptionsGetAPISubscribers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
