/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { asyncJobsListAsyncJob } from "../../funcs/asyncJobsListAsyncJob.js";
import { ListAsyncJobRequest$zodSchema } from "../../models/listasyncjobop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAsyncJobRequest$zodSchema,
};

export const tool$asyncJobsListAsyncJob: ToolDefinition<typeof args> = {
  name: "async-jobs-list-async-job",
  description: `List Async Jobs

Get the list of AsyncJobs.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await asyncJobsListAsyncJob(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
