/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGetCategoryApisPage } from "../../funcs/categoriesGetCategoryApisPage.js";
import { GetCategoryApisPageRequest$zodSchema } from "../../models/getcategoryapispageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCategoryApisPageRequest$zodSchema,
};

export const tool$categoriesGetCategoryApisPage: ToolDefinition<typeof args> = {
  name: "categories-get-category-apis-page",
  description: `Page of APIs within a Category`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesGetCategoryApisPage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
