/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesUpdateCategoryApi } from "../../funcs/categoriesUpdateCategoryApi.js";
import { UpdateCategoryApiRequest$zodSchema } from "../../models/updatecategoryapiop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateCategoryApiRequest$zodSchema,
};

export const tool$categoriesUpdateCategoryApi: ToolDefinition<typeof args> = {
  name: "update_category_api",
  description: `Update a specified API within a Category`,
  scopes: ["write"],
  annotations: {
    "title": "Update Category Api",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await categoriesUpdateCategoryApi(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
