/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsListGroups } from "../../funcs/groupsListGroups.js";
import { ListGroupsRequest$zodSchema } from "../../models/listgroupsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListGroupsRequest$zodSchema,
};

export const tool$groupsListGroups: ToolDefinition<typeof args> = {
  name: "groups-list-groups",
  description: `List of environment groups

List the groups of a given environment.

User must have the ENVIRONMENT_GROUP[READ] permission.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await groupsListGroups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
