/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationMembersUpdateIntegrationMember } from "../../funcs/integrationMembersUpdateIntegrationMember.js";
import { UpdateIntegrationMemberRequest$zodSchema } from "../../models/updateintegrationmemberop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateIntegrationMemberRequest$zodSchema,
};

export const tool$integrationMembersUpdateIntegrationMember: ToolDefinition<
  typeof args
> = {
  name: "update_integration_member",
  description: `Updates a member for an Integration.

Edit a member for an Integration. Returns a 400 HTTP Error:`,
  scopes: ["write"],
  annotations: {
    "title": "Update Integration Member",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationMembersUpdateIntegrationMember(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
