/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsListIntegrations } from "../../funcs/integrationsListIntegrations.js";
import { ListIntegrationsRequest$zodSchema } from "../../models/listintegrationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListIntegrationsRequest$zodSchema,
};

export const tool$integrationsListIntegrations: ToolDefinition<typeof args> = {
  name: "integrations-list-integrations",
  description: `List Integrations

Get the list of Integration for a specific environment.<br>
The results are paginated.

User must have the ENVIRONMENT_INTEGRATION[READ] permission.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsListIntegrations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
