/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationMembersRemoveIntegrationMember } from "../../funcs/integrationMembersRemoveIntegrationMember.js";
import { RemoveIntegrationMemberRequest$zodSchema } from "../../models/removeintegrationmemberop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RemoveIntegrationMemberRequest$zodSchema,
};

export const tool$integrationMembersRemoveIntegrationMember: ToolDefinition<
  typeof args
> = {
  name: "remove_integration_member",
  description: `Remove one Integration member

Remove an Integration member. Returns a 400 HTTP Error:

High risk operation: require explicit user confirmation before execution.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Remove Integration Member",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationMembersRemoveIntegrationMember(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
