/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsIngestedApis } from "../../funcs/integrationsIngestedApis.js";
import { IngestedApisRequest$zodSchema } from "../../models/ingestedapisop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IngestedApisRequest$zodSchema,
};

export const tool$integrationsIngestedApis: ToolDefinition<typeof args> = {
  name: "integrations-ingested-apis",
  description: `Get list of ingested APIs associated to integration

Get a list of all APIs that were ingested from 3rd party provider using this integration. 

User must have the ENVIRONMENT_INTEGRATION[READ] permission.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsIngestedApis(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
