/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsDeleteIntegration } from "../../funcs/integrationsDeleteIntegration.js";
import { DeleteIntegrationRequest$zodSchema } from "../../models/deleteintegrationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteIntegrationRequest$zodSchema,
};

export const tool$integrationsDeleteIntegration: ToolDefinition<typeof args> = {
  name: "delete_integration",
  description: `Delete Integration

Delete specific integration To delete integration user must have ENVIRONMENT_INTEGRATION[DELETE] permission. Deletion is not possible if there is any federated API associated.

High risk operation: require explicit user confirmation before execution.`,
  scopes: ["write", "dangerous"],
  annotations: {
    "title": "Delete Integration",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsDeleteIntegration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
