/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsPreviewIntegration } from "../../funcs/integrationsPreviewIntegration.js";
import { PreviewIntegrationRequest$zodSchema } from "../../models/previewintegrationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PreviewIntegrationRequest$zodSchema,
};

export const tool$integrationsPreviewIntegration: ToolDefinition<typeof args> =
  {
    name: "preview_integration",
    description: `Preview APIs to ingest for a specific Integration

Preview APIs to ingest before actual ingestion. to perform ingestion preview.`,
    scopes: ["read"],
    annotations: {
      "title": "Preview Integration",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await integrationsPreviewIntegration(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
