/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationMembersListIntegrationMembers } from "../../funcs/integrationMembersListIntegrationMembers.js";
import { ListIntegrationMembersRequest$zodSchema } from "../../models/listintegrationmembersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListIntegrationMembersRequest$zodSchema,
};

export const tool$integrationMembersListIntegrationMembers: ToolDefinition<
  typeof args
> = {
  name: "integration-members-list-integration-members",
  description: `Get the Integration's members

List the members for a given Integration.

User must have the INTEGRATION_MEMBER[READ] permission.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationMembersListIntegrationMembers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
