/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { GraviteeApimCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$apiAnalyticsGetAPIAnalyticsRequestCount } from "./tools/apiAnalyticsGetAPIAnalyticsRequestCount.js";
import { tool$apiAnalyticsGetAPILog } from "./tools/apiAnalyticsGetAPILog.js";
import { tool$apiAnalyticsGetAPILogs } from "./tools/apiAnalyticsGetAPILogs.js";
import { tool$apiAnalyticsGetAPIMessageLogs } from "./tools/apiAnalyticsGetAPIMessageLogs.js";
import { tool$apiAnalyticsGetAverageConnectionDuration } from "./tools/apiAnalyticsGetAverageConnectionDuration.js";
import { tool$apiAnalyticsGetAverageMessagesPerRequest } from "./tools/apiAnalyticsGetAverageMessagesPerRequest.js";
import { tool$apiAnalyticsGetResponseStatusCodes } from "./tools/apiAnalyticsGetResponseStatusCodes.js";
import { tool$apiAnalyticsGetResponseStatusOvertime } from "./tools/apiAnalyticsGetResponseStatusOvertime.js";
import { tool$apiAnalyticsGetResponseTimeOverTime } from "./tools/apiAnalyticsGetResponseTimeOverTime.js";
import { tool$apiAuditsGetAPIAudits } from "./tools/apiAuditsGetAPIAudits.js";
import { tool$apiAuditsListAPIAuditEvents } from "./tools/apiAuditsListAPIAuditEvents.js";
import { tool$apiDocumentationCreateDocumentationPage } from "./tools/apiDocumentationCreateDocumentationPage.js";
import { tool$apiDocumentationDeleteDocumentationPage } from "./tools/apiDocumentationDeleteDocumentationPage.js";
import { tool$apiDocumentationFetchDocumentationPage } from "./tools/apiDocumentationFetchDocumentationPage.js";
import { tool$apiDocumentationGetAPIPage } from "./tools/apiDocumentationGetAPIPage.js";
import { tool$apiDocumentationGetAPIPages } from "./tools/apiDocumentationGetAPIPages.js";
import { tool$apiDocumentationPublishDocumentationPage } from "./tools/apiDocumentationPublishDocumentationPage.js";
import { tool$apiDocumentationUnpublishDocumentationPage } from "./tools/apiDocumentationUnpublishDocumentationPage.js";
import { tool$apiDocumentationUpdateDocumentationPage } from "./tools/apiDocumentationUpdateDocumentationPage.js";
import { tool$apiEventsGetAPIEventById } from "./tools/apiEventsGetAPIEventById.js";
import { tool$apiEventsGetAPIEvents } from "./tools/apiEventsGetAPIEvents.js";
import { tool$apiHealthGetAPIAvailability } from "./tools/apiHealthGetAPIAvailability.js";
import { tool$apiHealthGetAPIHealthAverageResponseTime } from "./tools/apiHealthGetAPIHealthAverageResponseTime.js";
import { tool$apiHealthGetAPIHealthAverageResponseTimeOvertime } from "./tools/apiHealthGetAPIHealthAverageResponseTimeOvertime.js";
import { tool$apiHealthGetAPIHealthLogs } from "./tools/apiHealthGetAPIHealthLogs.js";
import { tool$apiMembersAddAPIMember } from "./tools/apiMembersAddAPIMember.js";
import { tool$apiMembersListAPIMembers } from "./tools/apiMembersListAPIMembers.js";
import { tool$apiMembersRemoveAPIMember } from "./tools/apiMembersRemoveAPIMember.js";
import { tool$apiMembersUpdateAPIMember } from "./tools/apiMembersUpdateAPIMember.js";
import { tool$apiPlansCloseAPIPlan } from "./tools/apiPlansCloseAPIPlan.js";
import { tool$apiPlansCreateAPIPlan } from "./tools/apiPlansCreateAPIPlan.js";
import { tool$apiPlansDeleteAPIPlan } from "./tools/apiPlansDeleteAPIPlan.js";
import { tool$apiPlansDeprecateAPIPlan } from "./tools/apiPlansDeprecateAPIPlan.js";
import { tool$apiPlansGetAPIPlan } from "./tools/apiPlansGetAPIPlan.js";
import { tool$apiPlansListAPIPlans } from "./tools/apiPlansListAPIPlans.js";
import { tool$apiPlansPublishAPIPlan } from "./tools/apiPlansPublishAPIPlan.js";
import { tool$apiPlansUpdateAPIPlan } from "./tools/apiPlansUpdateAPIPlan.js";
import { tool$apiScoringGetAPIScoring } from "./tools/apiScoringGetAPIScoring.js";
import { tool$apiScoringTriggerAPIScoring } from "./tools/apiScoringTriggerAPIScoring.js";
import { tool$apIsCreateApi } from "./tools/apIsCreateApi.js";
import { tool$apIsCreateApiDeployment } from "./tools/apIsCreateApiDeployment.js";
import { tool$apIsCreateApiFromSwagger } from "./tools/apIsCreateApiFromSwagger.js";
import { tool$apIsCreateApiWithImportDefinition } from "./tools/apIsCreateApiWithImportDefinition.js";
import { tool$apIsDeleteApi } from "./tools/apIsDeleteApi.js";
import { tool$apIsDeleteApiBackground } from "./tools/apIsDeleteApiBackground.js";
import { tool$apIsDeleteApiPicture } from "./tools/apIsDeleteApiPicture.js";
import { tool$apIsDuplicateApi } from "./tools/apIsDuplicateApi.js";
import { tool$apIsExportApiDefinition } from "./tools/apIsExportApiDefinition.js";
import { tool$apIsGetApi } from "./tools/apIsGetApi.js";
import { tool$apIsGetApiBackground } from "./tools/apIsGetApiBackground.js";
import { tool$apIsGetApiMetadata } from "./tools/apIsGetApiMetadata.js";
import { tool$apIsGetApiPicture } from "./tools/apIsGetApiPicture.js";
import { tool$apIsGetCurrentApiDeployment } from "./tools/apIsGetCurrentApiDeployment.js";
import { tool$apIsListApis } from "./tools/apIsListApis.js";
import { tool$apiSpecGenGetSpecGenState } from "./tools/apiSpecGenGetSpecGenState.js";
import { tool$apiSpecGenPost } from "./tools/apiSpecGenPost.js";
import { tool$apIsReviewsAccept } from "./tools/apIsReviewsAccept.js";
import { tool$apIsReviewsAsk } from "./tools/apIsReviewsAsk.js";
import { tool$apIsReviewsReject } from "./tools/apIsReviewsReject.js";
import { tool$apIsRollbackApi } from "./tools/apIsRollbackApi.js";
import { tool$apIsSearchApis } from "./tools/apIsSearchApis.js";
import { tool$apIsStartApi } from "./tools/apIsStartApi.js";
import { tool$apIsStopApi } from "./tools/apIsStopApi.js";
import { tool$apIsTransferOwnership } from "./tools/apIsTransferOwnership.js";
import { tool$apiSubscriptionsAcceptAPISubscription } from "./tools/apiSubscriptionsAcceptAPISubscription.js";
import { tool$apiSubscriptionsCloseAPISubscription } from "./tools/apiSubscriptionsCloseAPISubscription.js";
import { tool$apiSubscriptionsCreateAPISubscription } from "./tools/apiSubscriptionsCreateAPISubscription.js";
import { tool$apiSubscriptionsExportAPISubscriptions } from "./tools/apiSubscriptionsExportAPISubscriptions.js";
import { tool$apiSubscriptionsGetAPISubscribers } from "./tools/apiSubscriptionsGetAPISubscribers.js";
import { tool$apiSubscriptionsGetAPISubscription } from "./tools/apiSubscriptionsGetAPISubscription.js";
import { tool$apiSubscriptionsGetAPISubscriptionAPIKeys } from "./tools/apiSubscriptionsGetAPISubscriptionAPIKeys.js";
import { tool$apiSubscriptionsGetAPISubscriptions } from "./tools/apiSubscriptionsGetAPISubscriptions.js";
import { tool$apiSubscriptionsPauseAPISubscription } from "./tools/apiSubscriptionsPauseAPISubscription.js";
import { tool$apiSubscriptionsReactivateAPISubscriptionAPIKey } from "./tools/apiSubscriptionsReactivateAPISubscriptionAPIKey.js";
import { tool$apiSubscriptionsRejectAPISubscription } from "./tools/apiSubscriptionsRejectAPISubscription.js";
import { tool$apiSubscriptionsRenewAPISubscriptionAPIKeys } from "./tools/apiSubscriptionsRenewAPISubscriptionAPIKeys.js";
import { tool$apiSubscriptionsResumeAPISubscription } from "./tools/apiSubscriptionsResumeAPISubscription.js";
import { tool$apiSubscriptionsRevokeAPISubscriptionAPIKey } from "./tools/apiSubscriptionsRevokeAPISubscriptionAPIKey.js";
import { tool$apiSubscriptionsTransferAPISubscription } from "./tools/apiSubscriptionsTransferAPISubscription.js";
import { tool$apiSubscriptionsUpdateAPISubscription } from "./tools/apiSubscriptionsUpdateAPISubscription.js";
import { tool$apiSubscriptionsUpdateAPISubscriptionAPIKey } from "./tools/apiSubscriptionsUpdateAPISubscriptionAPIKey.js";
import { tool$apiSubscriptionsVerifyAPIDeployment } from "./tools/apiSubscriptionsVerifyAPIDeployment.js";
import { tool$apiSubscriptionsVerifyCreateAPISubscription } from "./tools/apiSubscriptionsVerifyCreateAPISubscription.js";
import { tool$apIsUpdateApi } from "./tools/apIsUpdateApi.js";
import { tool$apIsUpdateApiBackground } from "./tools/apIsUpdateApiBackground.js";
import { tool$apIsUpdateApiPicture } from "./tools/apIsUpdateApiPicture.js";
import { tool$apIsVerifyHosts } from "./tools/apIsVerifyHosts.js";
import { tool$apIsVerifyPaths } from "./tools/apIsVerifyPaths.js";
import { tool$asyncJobsListAsyncJob } from "./tools/asyncJobsListAsyncJob.js";
import { tool$categoriesGetCategoryApisPage } from "./tools/categoriesGetCategoryApisPage.js";
import { tool$categoriesUpdateCategoryApi } from "./tools/categoriesUpdateCategoryApi.js";
import { tool$groupsListGroupMembers } from "./tools/groupsListGroupMembers.js";
import { tool$groupsListGroups } from "./tools/groupsListGroups.js";
import { tool$integrationMembersAddIntegrationMember } from "./tools/integrationMembersAddIntegrationMember.js";
import { tool$integrationMembersListIntegrationMembers } from "./tools/integrationMembersListIntegrationMembers.js";
import { tool$integrationMembersRemoveIntegrationMember } from "./tools/integrationMembersRemoveIntegrationMember.js";
import { tool$integrationMembersUpdateIntegrationMember } from "./tools/integrationMembersUpdateIntegrationMember.js";
import { tool$integrationsCreateIntegration } from "./tools/integrationsCreateIntegration.js";
import { tool$integrationsDeleteIngestedApis } from "./tools/integrationsDeleteIngestedApis.js";
import { tool$integrationsDeleteIntegration } from "./tools/integrationsDeleteIntegration.js";
import { tool$integrationsGetIntegration } from "./tools/integrationsGetIntegration.js";
import { tool$integrationsIngestedApis } from "./tools/integrationsIngestedApis.js";
import { tool$integrationsIngestIntegration } from "./tools/integrationsIngestIntegration.js";
import { tool$integrationsListIntegrations } from "./tools/integrationsListIntegrations.js";
import { tool$integrationsPreviewIntegration } from "./tools/integrationsPreviewIntegration.js";
import { tool$integrationsUpdateIntegration } from "./tools/integrationsUpdateIntegration.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => GraviteeApimCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  protocol?: SDKOptions["protocol"] | undefined;
  managementAPIHost?: SDKOptions["managementAPIHost"] | undefined;
  orgId?: SDKOptions["orgId"] | undefined;
}) {
  const server = new McpServer({
    name: "GraviteeApim",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new GraviteeApimCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      protocol: deps.protocol,
      managementAPIHost: deps.managementAPIHost,
      orgId: deps.orgId,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$apIsListApis);
  tool(tool$apIsCreateApi);
  tool(tool$apIsCreateApiFromSwagger);
  tool(tool$apIsCreateApiWithImportDefinition);
  tool(tool$apIsSearchApis);
  tool(tool$apIsVerifyPaths);
  tool(tool$apIsVerifyHosts);
  tool(tool$apIsGetApi);
  tool(tool$apIsUpdateApi);
  tool(tool$apIsDeleteApi);
  tool(tool$apIsGetApiBackground);
  tool(tool$apIsUpdateApiBackground);
  tool(tool$apIsDeleteApiBackground);
  tool(tool$apIsCreateApiDeployment);
  tool(tool$apIsGetCurrentApiDeployment);
  tool(tool$apIsGetApiPicture);
  tool(tool$apIsUpdateApiPicture);
  tool(tool$apIsDeleteApiPicture);
  tool(tool$apIsGetApiMetadata);
  tool(tool$apIsExportApiDefinition);
  tool(tool$apIsStartApi);
  tool(tool$apIsStopApi);
  tool(tool$apIsTransferOwnership);
  tool(tool$apIsDuplicateApi);
  tool(tool$apIsRollbackApi);
  tool(tool$apIsReviewsAsk);
  tool(tool$apIsReviewsAccept);
  tool(tool$apIsReviewsReject);
  tool(tool$apiSubscriptionsVerifyAPIDeployment);
  tool(tool$apiSubscriptionsGetAPISubscribers);
  tool(tool$apiSubscriptionsGetAPISubscriptions);
  tool(tool$apiSubscriptionsCreateAPISubscription);
  tool(tool$apiSubscriptionsExportAPISubscriptions);
  tool(tool$apiSubscriptionsVerifyCreateAPISubscription);
  tool(tool$apiSubscriptionsGetAPISubscription);
  tool(tool$apiSubscriptionsUpdateAPISubscription);
  tool(tool$apiSubscriptionsCloseAPISubscription);
  tool(tool$apiSubscriptionsPauseAPISubscription);
  tool(tool$apiSubscriptionsResumeAPISubscription);
  tool(tool$apiSubscriptionsAcceptAPISubscription);
  tool(tool$apiSubscriptionsRejectAPISubscription);
  tool(tool$apiSubscriptionsTransferAPISubscription);
  tool(tool$apiSubscriptionsGetAPISubscriptionAPIKeys);
  tool(tool$apiSubscriptionsRenewAPISubscriptionAPIKeys);
  tool(tool$apiSubscriptionsUpdateAPISubscriptionAPIKey);
  tool(tool$apiSubscriptionsRevokeAPISubscriptionAPIKey);
  tool(tool$apiSubscriptionsReactivateAPISubscriptionAPIKey);
  tool(tool$apiMembersListAPIMembers);
  tool(tool$apiMembersAddAPIMember);
  tool(tool$apiMembersUpdateAPIMember);
  tool(tool$apiMembersRemoveAPIMember);
  tool(tool$apiPlansListAPIPlans);
  tool(tool$apiPlansCreateAPIPlan);
  tool(tool$apiPlansGetAPIPlan);
  tool(tool$apiPlansUpdateAPIPlan);
  tool(tool$apiPlansDeleteAPIPlan);
  tool(tool$apiPlansCloseAPIPlan);
  tool(tool$apiPlansDeprecateAPIPlan);
  tool(tool$apiPlansPublishAPIPlan);
  tool(tool$groupsListGroups);
  tool(tool$groupsListGroupMembers);
  tool(tool$integrationsListIntegrations);
  tool(tool$integrationsCreateIntegration);
  tool(tool$integrationsGetIntegration);
  tool(tool$integrationsUpdateIntegration);
  tool(tool$integrationsDeleteIntegration);
  tool(tool$integrationsIngestIntegration);
  tool(tool$integrationsPreviewIntegration);
  tool(tool$integrationsIngestedApis);
  tool(tool$integrationsDeleteIngestedApis);
  tool(tool$integrationMembersListIntegrationMembers);
  tool(tool$integrationMembersAddIntegrationMember);
  tool(tool$integrationMembersUpdateIntegrationMember);
  tool(tool$integrationMembersRemoveIntegrationMember);
  tool(tool$apiAnalyticsGetAPIAnalyticsRequestCount);
  tool(tool$apiAnalyticsGetAverageMessagesPerRequest);
  tool(tool$apiAnalyticsGetAverageConnectionDuration);
  tool(tool$apiAnalyticsGetResponseStatusCodes);
  tool(tool$apiAnalyticsGetResponseTimeOverTime);
  tool(tool$apiAnalyticsGetResponseStatusOvertime);
  tool(tool$apiAnalyticsGetAPILogs);
  tool(tool$apiAnalyticsGetAPILog);
  tool(tool$apiAnalyticsGetAPIMessageLogs);
  tool(tool$apiHealthGetAPIHealthAverageResponseTime);
  tool(tool$apiHealthGetAPIHealthAverageResponseTimeOvertime);
  tool(tool$apiHealthGetAPIAvailability);
  tool(tool$apiHealthGetAPIHealthLogs);
  tool(tool$apiAuditsGetAPIAudits);
  tool(tool$apiAuditsListAPIAuditEvents);
  tool(tool$apiEventsGetAPIEvents);
  tool(tool$apiEventsGetAPIEventById);
  tool(tool$apiDocumentationGetAPIPages);
  tool(tool$apiDocumentationCreateDocumentationPage);
  tool(tool$apiDocumentationGetAPIPage);
  tool(tool$apiDocumentationUpdateDocumentationPage);
  tool(tool$apiDocumentationDeleteDocumentationPage);
  tool(tool$apiDocumentationPublishDocumentationPage);
  tool(tool$apiDocumentationUnpublishDocumentationPage);
  tool(tool$apiDocumentationFetchDocumentationPage);
  tool(tool$apiSpecGenGetSpecGenState);
  tool(tool$apiSpecGenPost);
  tool(tool$apiScoringTriggerAPIScoring);
  tool(tool$apiScoringGetAPIScoring);
  tool(tool$categoriesGetCategoryApisPage);
  tool(tool$categoriesUpdateCategoryApi);
  tool(tool$asyncJobsListAsyncJob);

  return server;
}
