workflowVersion: 1.0.0
speakeasyVersion: 1.768.2
sources:
    Gravitee.io APIM - Management API - APIs:
        inputs:
            - location: ./.speakeasy/openapi-apis.yaml
        overlays:
            - location: ./.speakeasy/apim-mcp-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/gravitee/gravitee/gravitee-io-apim---management-api---ap-is
targets:
    gravitee-apim:
        target: mcp-typescript
        source: Gravitee.io APIM - Management API - APIs
