/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AcceptSubscription = {
  reason?: string | undefined;
  customApiKey?: string | undefined;
  startingAt?: string | undefined;
  endingAt?: string | undefined;
};

export const AcceptSubscription$zodSchema: z.ZodType<
  AcceptSubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  customApiKey: z.string().optional(),
  endingAt: z.string().datetime({ offset: true }).optional(),
  reason: z.string().optional(),
  startingAt: z.string().datetime({ offset: true }).optional(),
});
