/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddMember, AddMember$zodSchema } from "./addmember.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Member, Member$zodSchema } from "./member.js";

export type AddApiMemberRequest = {
  envId?: string | undefined;
  apiId: string;
  AddMember: AddMember;
};

export const AddApiMemberRequest$zodSchema: z.ZodType<AddApiMemberRequest> = z
  .object({
    AddMember: AddMember$zodSchema,
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  });

export type AddApiMemberResponse = Member | ErrorT;

export const AddApiMemberResponse$zodSchema: z.ZodType<AddApiMemberResponse> = z
  .union([
    Member$zodSchema,
    ErrorT$zodSchema,
  ]);
