/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddMember, AddMember$zodSchema } from "./addmember.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Member, Member$zodSchema } from "./member.js";

export type AddApiMemberRequest = {
  envId?: string | undefined;
  apiId: string;
  AddMember: AddMember;
};

export const AddApiMemberRequest$zodSchema: z.ZodType<
  AddApiMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AddMember: AddMember$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type AddApiMemberResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Member?: Member | undefined;
  ErrorT?: ErrorT | undefined;
};

export const AddApiMemberResponse$zodSchema: z.ZodType<
  AddApiMemberResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  Member: Member$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
