/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A Time range
 */
export type AnalyticTimeRange = {
  from?: number | undefined;
  to?: number | undefined;
  interval?: number | undefined;
};

export const AnalyticTimeRange$zodSchema: z.ZodType<
  AnalyticTimeRange,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.number().int().optional(),
  interval: z.number().int().optional(),
  to: z.number().int().optional(),
}).describe("A Time range");
