/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LoggingV4, LoggingV4$zodSchema } from "./loggingv4.js";
import { Sampling, Sampling$zodSchema } from "./sampling.js";
import { TracingV4, TracingV4$zodSchema } from "./tracingv4.js";

export type Analytics = {
  enabled?: boolean | undefined;
  sampling?: Sampling | undefined;
  logging?: LoggingV4 | undefined;
  tracing?: TracingV4 | undefined;
};

export const Analytics$zodSchema: z.ZodType<Analytics, z.ZodTypeDef, unknown> =
  z.object({
    enabled: z.boolean().default(true),
    logging: LoggingV4$zodSchema.optional(),
    sampling: Sampling$zodSchema.optional(),
    tracing: TracingV4$zodSchema.optional(),
  });
