/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A Time range
 */
export type AnalyticTimeRange = {
  from?: number | undefined;
  to?: number | undefined;
  interval?: number | undefined;
};

export const AnalyticTimeRange$zodSchema: z.ZodType<AnalyticTimeRange> = z
  .object({
    from: z.int().optional().describe("The timestamp starting the time range"),
    interval: z.int().optional().describe(
      "The interval in milliseconds splitting the data",
    ),
    to: z.int().optional().describe("The timestamp ending the time range"),
  }).describe("A Time range");
