/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiFederated, ApiFederated$zodSchema } from "./apifederated.js";
import {
  ApiFederatedAgent,
  ApiFederatedAgent$zodSchema,
} from "./apifederatedagent.js";
import { ApiV2, ApiV2$zodSchema } from "./apiv2.js";
import { ApiV4Output, ApiV4Output$zodSchema } from "./apiv4output.js";

export type Api =
  | (ApiV2 & { definitionVersion: "V2" })
  | (ApiV4Output & { definitionVersion: "V4" })
  | (ApiFederated & { definitionVersion: "FEDERATED" })
  | (ApiFederatedAgent & { definitionVersion: "FEDERATED_AGENT" });

export const Api$zodSchema: z.ZodType<Api> = z.union([
  ApiV2$zodSchema.and(
    z.object({
      definitionVersion: z.literal("V2"),
    }).transform((v) => ({ definitionVersion: v.definitionVersion })),
  ),
  ApiV4Output$zodSchema.and(
    z.object({
      definitionVersion: z.literal("V4"),
    }).transform((v) => ({ definitionVersion: v.definitionVersion })),
  ),
  ApiFederated$zodSchema.and(
    z.object({
      definitionVersion: z.literal("FEDERATED"),
    }).transform((v) => ({ definitionVersion: v.definitionVersion })),
  ),
  ApiFederatedAgent$zodSchema.and(
    z.object({
      definitionVersion: z.literal("FEDERATED_AGENT"),
    }).transform((v) => ({ definitionVersion: v.definitionVersion })),
  ),
]);
