/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * API Analytics for requests count by entrypoint.
 */
export type ApiAnalyticsRequestsCountResponse = {
  total?: number | undefined;
  countsByEntrypoint?: { [k: string]: number } | undefined;
};

export const ApiAnalyticsRequestsCountResponse$zodSchema: z.ZodType<
  ApiAnalyticsRequestsCountResponse
> = z.object({
  countsByEntrypoint: z.record(z.string(), z.number()).optional(),
  total: z.int().optional().describe("The total count of requests"),
}).describe("API Analytics for requests count by entrypoint.");
