/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnalyticTimeRange,
  AnalyticTimeRange$zodSchema,
} from "./analytictimerange.js";

/**
 * API Analytics integer data point on a period.
 */
export type ApiAnalyticsOverPeriodResponse = {
  timeRange?: AnalyticTimeRange | undefined;
  data?: Array<number> | undefined;
};

export const ApiAnalyticsOverPeriodResponse$zodSchema: z.ZodType<
  ApiAnalyticsOverPeriodResponse
> = z.object({
  data: z.array(z.int()).optional().describe(
    "Response time average (in milliseconds) over time",
  ),
  timeRange: AnalyticTimeRange$zodSchema.optional().describe("A Time range"),
}).describe("API Analytics integer data point on a period.");
