/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnalyticTimeRange,
  AnalyticTimeRange$zodSchema,
} from "./analytictimerange.js";

/**
 * API Analytics integer data point on a period.
 */
export type ApiAnalyticsOverPeriodResponse = {
  timeRange?: AnalyticTimeRange | undefined;
  data?: Array<number> | undefined;
};

export const ApiAnalyticsOverPeriodResponse$zodSchema: z.ZodType<
  ApiAnalyticsOverPeriodResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.number().int()).optional(),
  timeRange: AnalyticTimeRange$zodSchema.optional(),
}).describe("API Analytics integer data point on a period.");
