/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Breadcrumb, Breadcrumb$zodSchema } from "./breadcrumb.js";
import { Page, Page$zodSchema } from "./page.js";

/**
 * API documentation pages
 */
export type ApiDocumentationPagesResponse = {
  pages?: Array<Page> | undefined;
  breadcrumb?: Array<Breadcrumb> | undefined;
};

export const ApiDocumentationPagesResponse$zodSchema: z.ZodType<
  ApiDocumentationPagesResponse
> = z.object({
  breadcrumb: z.array(Breadcrumb$zodSchema).optional().describe(
    "Breadcrumb to the root folder. Only returned when parentId is specified.",
  ),
  pages: z.array(Page$zodSchema).optional(),
}).describe("API documentation pages");
