/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiEntrypoint = {
  target?: string | undefined;
  host?: string | undefined;
  tags?: Array<string> | undefined;
};

export const ApiEntrypoint$zodSchema: z.ZodType<ApiEntrypoint> = z.object({
  host: z.string().optional().describe("The host of the entrypoint."),
  tags: z.array(z.string()).optional().describe(
    "The list of sharding tags associated with this entrypoint.",
  ),
  target: z.string().optional().describe("The target of the entrypoint."),
});
