/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AnalyticTimeRange,
  AnalyticTimeRange$zodSchema,
} from "./analytictimerange.js";

/**
 * Average response time of an API Health-Check.
 */
export type ApiHealthAverageResponseTimeOvertimeResponse = {
  timeRange?: AnalyticTimeRange | undefined;
  data?: Array<number> | undefined;
};

export const ApiHealthAverageResponseTimeOvertimeResponse$zodSchema: z.ZodType<
  ApiHealthAverageResponseTimeOvertimeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.number().int()).optional(),
  timeRange: AnalyticTimeRange$zodSchema.optional(),
}).describe("Average response time of an API Health-Check.");
