/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HealthCheckLog, HealthCheckLog$zodSchema } from "./healthchecklog.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of HealthCheck logs
 */
export type ApiHealthLogsResponse = {
  data?: Array<HealthCheckLog> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const ApiHealthLogsResponse$zodSchema: z.ZodType<ApiHealthLogsResponse> =
  z.object({
    data: z.array(HealthCheckLog$zodSchema).optional().describe(
      "List of health check logs.",
    ),
    links: Links$zodSchema.optional().describe("List of links for pagination"),
    pagination: Pagination$zodSchema.optional().describe(
      "Generic object to handle pagination data.",
    ),
  }).describe("Page of HealthCheck logs");
