/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The list of headers associated with this message.
 */
export type ApiLogResponseContentHeaders = {};

export const ApiLogResponseContentHeaders$zodSchema: z.ZodType<
  ApiLogResponseContentHeaders
> = z.object({}).describe("The list of headers associated with this message.");

/**
 * The log response content.
 */
export type ApiLogResponseContent = {
  status?: number | undefined;
  headers?: ApiLogResponseContentHeaders | undefined;
  body?: string | undefined;
};

export const ApiLogResponseContent$zodSchema: z.ZodType<ApiLogResponseContent> =
  z.object({
    body: z.string().optional().describe("The response's body."),
    headers: z.lazy(() => ApiLogResponseContentHeaders$zodSchema).optional()
      .describe("The list of headers associated with this message."),
    status: z.int().optional().describe("The response's status."),
  }).describe("The log response content.");
