/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HttpMethod, HttpMethod$zodSchema } from "./httpmethod.js";

/**
 * The list of headers associated with this message.
 */
export type ApiLogRequestContentHeaders = {};

export const ApiLogRequestContentHeaders$zodSchema: z.ZodType<
  ApiLogRequestContentHeaders
> = z.object({}).describe("The list of headers associated with this message.");

/**
 * The log request content.
 */
export type ApiLogRequestContent = {
  method?: HttpMethod | undefined;
  uri?: string | undefined;
  headers?: ApiLogRequestContentHeaders | undefined;
  body?: string | undefined;
};

export const ApiLogRequestContent$zodSchema: z.ZodType<ApiLogRequestContent> = z
  .object({
    body: z.string().optional().describe("The request's body."),
    headers: z.lazy(() => ApiLogRequestContentHeaders$zodSchema).optional()
      .describe("The list of headers associated with this message."),
    method: HttpMethod$zodSchema.optional().describe(
      "The method of the selector",
    ),
    uri: z.string().optional().describe("URI of the request."),
  }).describe("The log request content.");
