/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HttpMethod, HttpMethod$zodSchema } from "./httpmethod.js";

/**
 * The list of headers associated with this message.
 */
export type ApiLogRequestContentHeaders = {};

export const ApiLogRequestContentHeaders$zodSchema: z.ZodType<
  ApiLogRequestContentHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("The list of headers associated with this message.");

/**
 * The log request content.
 */
export type ApiLogRequestContent = {
  method?: HttpMethod | undefined;
  uri?: string | undefined;
  headers?: ApiLogRequestContentHeaders | undefined;
  body?: string | undefined;
};

export const ApiLogRequestContent$zodSchema: z.ZodType<
  ApiLogRequestContent,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string().optional(),
  headers: z.lazy(() => ApiLogRequestContentHeaders$zodSchema).optional(),
  method: HttpMethod$zodSchema.optional(),
  uri: z.string().optional(),
}).describe("The log request content.");
