/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ApiMetadataSourceParam$zodSchema = z.enum([
  "GLOBAL",
  "API",
]);

export type ApiMetadataSourceParam = z.infer<
  typeof ApiMetadataSourceParam$zodSchema
>;
