/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The list of headers associated with this message.
 */
export type ApiMessageLogContentHeaders = {};

export const ApiMessageLogContentHeaders$zodSchema: z.ZodType<
  ApiMessageLogContentHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("The list of headers associated with this message.");

/**
 * The list of Message's metadata.
 */
export type ApiMessageLogContentMetadata = {};

export const ApiMessageLogContentMetadata$zodSchema: z.ZodType<
  ApiMessageLogContentMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("The list of Message's metadata.");

/**
 * The message content.
 */
export type ApiMessageLogContent = {
  id?: string | undefined;
  connectorId?: string | undefined;
  payload?: string | undefined;
  isError?: boolean | undefined;
  headers?: ApiMessageLogContentHeaders | undefined;
  metadata?: ApiMessageLogContentMetadata | undefined;
};

export const ApiMessageLogContent$zodSchema: z.ZodType<
  ApiMessageLogContent,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectorId: z.string().optional(),
  headers: z.lazy(() => ApiMessageLogContentHeaders$zodSchema).optional(),
  id: z.string().optional(),
  isError: z.boolean().optional(),
  metadata: z.lazy(() => ApiMessageLogContentMetadata$zodSchema).optional(),
  payload: z.string().optional(),
}).describe("The message content.");
