/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiMessageLogContent,
  ApiMessageLogContent$zodSchema,
} from "./apimessagelogcontent.js";

export type ApiMessageLog = {
  requestId?: string | undefined;
  timestamp?: string | undefined;
  clientIdentifier?: string | undefined;
  correlationId?: string | undefined;
  parentCorrelationId?: string | undefined;
  operation?: string | undefined;
  entrypoint?: ApiMessageLogContent | undefined;
  endpoint?: ApiMessageLogContent | undefined;
};

export const ApiMessageLog$zodSchema: z.ZodType<
  ApiMessageLog,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientIdentifier: z.string().optional(),
  correlationId: z.string().optional(),
  endpoint: ApiMessageLogContent$zodSchema.optional(),
  entrypoint: ApiMessageLogContent$zodSchema.optional(),
  operation: z.string().optional(),
  parentCorrelationId: z.string().optional(),
  requestId: z.string().optional(),
  timestamp: z.string().datetime({ offset: true }).optional(),
});
