/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Info of an API Product that includes the given API — id and name only.
 */
export type ApiProductInfo = { id: string; name: string };

export const ApiProductInfo$zodSchema: z.ZodType<ApiProductInfo> = z.object({
  id: z.string().describe("The API Product ID"),
  name: z.string().describe("The API Product name"),
}).describe(
  "Info of an API Product that includes the given API — id and name only.",
);
