/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiReview = { message?: string | undefined };

export const ApiReview$zodSchema: z.ZodType<ApiReview, z.ZodTypeDef, unknown> =
  z.object({
    message: z.string().optional(),
  });
