/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiRollback = { eventId?: string | undefined };

export const ApiRollback$zodSchema: z.ZodType<
  ApiRollback,
  z.ZodTypeDef,
  unknown
> = z.object({
  eventId: z.string().optional(),
});
