/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiScoringPosition = {
  line?: number | undefined;
  character?: number | undefined;
};

export const ApiScoringPosition$zodSchema: z.ZodType<ApiScoringPosition> = z
  .object({
    character: z.int().optional().describe(
      "An integer that represents the character position within the line where the issue starts or ends. The value is zero indexed.",
    ),
    line: z.int().optional().describe(
      "An integer that represents the line number within the line where the issue starts or ends. The value is zero indexed.",
    ),
  });
