/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiScoringError = {
  code?: string | undefined;
  path?: Array<string> | undefined;
};

export const ApiScoringError$zodSchema: z.ZodType<
  ApiScoringError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  path: z.array(z.string()).optional(),
});
