/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ScoringStatus, ScoringStatus$zodSchema } from "./scoringstatus.js";

export type ApiScoringTriggerResponse = {
  status?: ScoringStatus | undefined;
  message?: string | undefined;
};

export const ApiScoringTriggerResponse$zodSchema: z.ZodType<
  ApiScoringTriggerResponse
> = z.object({
  message: z.string().optional().describe("Api Scoring message."),
  status: ScoringStatus$zodSchema.optional().describe("API Scoring status."),
});
