/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DynamicPropertyService,
  DynamicPropertyService$zodSchema,
} from "./dynamicpropertyservice.js";
import {
  HealthCheckService,
  HealthCheckService$zodSchema,
} from "./healthcheckservice.js";

export type ApiServicesV2 = {
  dynamicProperty?: DynamicPropertyService | undefined;
  healthCheck?: HealthCheckService | undefined;
};

export const ApiServicesV2$zodSchema: z.ZodType<
  ApiServicesV2,
  z.ZodTypeDef,
  unknown
> = z.object({
  dynamicProperty: DynamicPropertyService$zodSchema.optional(),
  healthCheck: HealthCheckService$zodSchema.optional(),
});
