/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";

export type ApiSearchQuery = {
  query?: string | undefined;
  ids?: Array<string> | undefined;
  definitionVersion?: DefinitionVersion | undefined;
  definitionVersions?: Array<DefinitionVersion> | undefined;
};

export const ApiSearchQuery$zodSchema: z.ZodType<
  ApiSearchQuery,
  z.ZodTypeDef,
  unknown
> = z.object({
  definitionVersion: DefinitionVersion$zodSchema.optional(),
  definitionVersions: z.array(DefinitionVersion$zodSchema).optional(),
  ids: z.array(z.string()).optional(),
  query: z.string().optional(),
});
