/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiScoringAsset,
  ApiScoringAsset$zodSchema,
} from "./apiscoringasset.js";
import {
  ApiScoringSummary,
  ApiScoringSummary$zodSchema,
} from "./apiscoringsummary.js";

export type ApiScoring = {
  createdAt?: string | undefined;
  summary?: ApiScoringSummary | undefined;
  assets?: Array<ApiScoringAsset> | undefined;
};

export const ApiScoring$zodSchema: z.ZodType<
  ApiScoring,
  z.ZodTypeDef,
  unknown
> = z.object({
  assets: z.array(ApiScoringAsset$zodSchema).optional(),
  createdAt: z.string().datetime({ offset: true }).optional(),
  summary: ApiScoringSummary$zodSchema.optional(),
});
