/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ApisSearchExpandsParam = {
  DeploymentState: "deploymentState",
} as const;
export type ApisSearchExpandsParam = ClosedEnum<typeof ApisSearchExpandsParam>;

export const ApisSearchExpandsParam$zodSchema = z.enum([
  "deploymentState",
]);
