/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ApisGetExpandsParam = {
  DeploymentState: "deploymentState",
  PrimaryOwner: "primaryOwner",
  Metadata: "metadata",
} as const;
export type ApisGetExpandsParam = ClosedEnum<typeof ApisGetExpandsParam>;

export const ApisGetExpandsParam$zodSchema = z.enum([
  "deploymentState",
  "primaryOwner",
  "metadata",
]);
