/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiScoringSummary = {
  score?: number | undefined;
  all?: number | undefined;
  errors?: number | undefined;
  warnings?: number | undefined;
  infos?: number | undefined;
  hints?: number | undefined;
};

export const ApiScoringSummary$zodSchema: z.ZodType<ApiScoringSummary> = z
  .object({
    all: z.int().optional().describe(
      "The total number of violated rules for all assets.",
    ),
    errors: z.int().optional().describe(
      "The total number of violated rules with severity ERROR for all assets.",
    ),
    hints: z.int().optional().describe(
      "The total number of violated rules with severity HINT for all assets.",
    ),
    infos: z.int().optional().describe(
      "The total number of violated rules with severity INFO for all assets.",
    ),
    score: z.number().optional().describe("The score of the API."),
    warnings: z.int().optional().describe(
      "The total number of violated rules with severity WARN for all assets.",
    ),
  });
