/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MembershipMemberType,
  MembershipMemberType$zodSchema,
} from "./membershipmembertype.js";

export type ApiTransferOwnership = {
  userId?: string | undefined;
  userReference?: string | undefined;
  userType?: MembershipMemberType | undefined;
  poRole?: string | undefined;
};

export const ApiTransferOwnership$zodSchema: z.ZodType<ApiTransferOwnership> = z
  .object({
    poRole: z.string().optional().describe(
      "The name of the role that will be assigned to the current primary owner after the transfer.",
    ),
    userId: z.string().optional().describe(
      "The new primary owner ID (user's technical identifier). Can be null if userReference is defined.",
    ),
    userReference: z.string().optional().describe(
      "The new primary owner reference (user's reference provided by an identity provider). Can be null if userId is defined.",
    ),
    userType: MembershipMemberType$zodSchema.optional().describe(
      "The type of membership",
    ),
  });
