/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the API regarding the review feature.
 */
export const ApiWorkflowState$zodSchema = z.enum([
  "DRAFT",
  "IN_REVIEW",
  "REQUEST_FOR_CHANGES",
  "REVIEW_OK",
]).describe("The status of the API regarding the review feature.");

export type ApiWorkflowState = z.infer<typeof ApiWorkflowState$zodSchema>;
