/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AsyncJob, AsyncJob$zodSchema } from "./asyncjob.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of async jobs
 */
export type AsyncJobsResponse = {
  data?: Array<AsyncJob> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const AsyncJobsResponse$zodSchema: z.ZodType<
  AsyncJobsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AsyncJob$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of async jobs");
