/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Audit, Audit$zodSchema } from "./audit.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of Audit
 */
export type AuditsResponse = {
  data?: Array<Audit> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const AuditsResponse$zodSchema: z.ZodType<
  AuditsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Audit$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of Audit");
