/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Audit events response
 */
export type AuditEventsResponse = { data?: Array<string> | undefined };

export const AuditEventsResponse$zodSchema: z.ZodType<
  AuditEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.string()).optional(),
}).describe("Audit events response");
