/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of the auditable element
 */
export const AuditReferenceType = {
  Api: "API",
  Application: "APPLICATION",
  Environment: "ENVIRONMENT",
  Organization: "ORGANIZATION",
} as const;
/**
 * The type of the auditable element
 */
export type AuditReferenceType = ClosedEnum<typeof AuditReferenceType>;

export const AuditReferenceType$zodSchema = z.enum([
  "API",
  "APPLICATION",
  "ENVIRONMENT",
  "ORGANIZATION",
]).describe("The type of the auditable element");

export type AuditReference = {
  id?: string | undefined;
  type?: AuditReferenceType | undefined;
  name?: string | undefined;
};

export const AuditReference$zodSchema: z.ZodType<AuditReference> = z.object({
  id: z.string().optional().describe("The id of the auditable element."),
  name: z.string().optional().describe("The name of the auditable element"),
  type: AuditReferenceType$zodSchema.optional().describe(
    "The type of the auditable element",
  ),
});
