/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PlanMode, PlanMode$zodSchema } from "./planmode.js";
import { PlanSecurity, PlanSecurity$zodSchema } from "./plansecurity.js";

export type BasePlan = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  apiId?: string | undefined;
  apiProductId?: string | undefined;
  security?: PlanSecurity | undefined;
  mode?: PlanMode | undefined;
};

export const BasePlan$zodSchema: z.ZodType<BasePlan> = z.object({
  apiId: z.string().optional().describe("Id of the API owning the plan."),
  apiProductId: z.string().optional().describe(
    "Id of the API Product owning the plan. Present only when the plan belongs to an API Product (omitted for API plans).",
  ),
  description: z.string().optional().describe(
    "Plan's description. A short description of your plan.",
  ),
  id: z.string().optional().describe("Plan's uuid."),
  mode: PlanMode$zodSchema.optional().describe(
    "The behavioural mode of the Plan (Standard for classical plan, Push for subscription plan).",
  ),
  name: z.string().optional().describe(
    "Plan's name. Duplicate names can exists.",
  ),
  security: PlanSecurity$zodSchema.optional(),
});
