/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The configuration of the step
 */
export type BaseStepConfiguration = {};

export const BaseStepConfiguration$zodSchema: z.ZodType<BaseStepConfiguration> =
  z.object({}).describe("The configuration of the step");

export type BaseStep = {
  name?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  policy?: string | undefined;
  configuration?: BaseStepConfiguration | undefined;
  condition?: string | undefined;
};

export const BaseStep$zodSchema: z.ZodType<BaseStep> = z.object({
  condition: z.string().optional().describe("The condition of the step"),
  configuration: z.lazy(() => BaseStepConfiguration$zodSchema).optional()
    .describe("The configuration of the step"),
  description: z.string().optional().describe("The description of the step"),
  enabled: z.boolean().default(true).describe("Is the step enabled or not."),
  name: z.string().optional().describe("The name of the step"),
  policy: z.string().optional().describe("The policy of the step"),
});
