/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BaseSubscription = { id?: string | undefined };

export const BaseSubscription$zodSchema: z.ZodType<BaseSubscription> = z.object(
  {
    id: z.string().optional().describe("Subscription's uuid."),
  },
);
