/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKeyMode, ApiKeyMode$zodSchema } from "./apikeymode.js";
import { PrimaryOwner, PrimaryOwner$zodSchema } from "./primaryowner.js";

export type BaseApplication = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  domain?: string | undefined;
  type?: string | undefined;
  primaryOwner?: PrimaryOwner | undefined;
  apiKeyMode?: ApiKeyMode | undefined;
};

export const BaseApplication$zodSchema: z.ZodType<BaseApplication> = z.object({
  apiKeyMode: ApiKeyMode$zodSchema.optional().describe(
    "The mode of an application regarding ApiKey plans.\n* UNSPECIFIED: no selected mode yet\n* EXCLUSIVE: an API Key is generated for each new subscription\n* SHARED: reuse always the same API Key for all subscriptions\n",
  ),
  description: z.string().optional().describe(
    "Application's description. A short description of your App.",
  ),
  domain: z.string().optional().describe(
    "Application's domain. Domain used by application, if relevant.",
  ),
  id: z.string().optional().describe("Application's uuid."),
  name: z.string().optional().describe(
    "Application's name. Duplicate names can exist.",
  ),
  primaryOwner: PrimaryOwner$zodSchema.optional(),
  type: z.string().optional().describe("Application's type."),
});
