/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKeyMode, ApiKeyMode$zodSchema } from "./apikeymode.js";
import { PrimaryOwner, PrimaryOwner$zodSchema } from "./primaryowner.js";

export type BaseApplication = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  domain?: string | undefined;
  type?: string | undefined;
  primaryOwner?: PrimaryOwner | undefined;
  apiKeyMode?: ApiKeyMode | undefined;
};

export const BaseApplication$zodSchema: z.ZodType<
  BaseApplication,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyMode: ApiKeyMode$zodSchema.optional(),
  description: z.string().optional(),
  domain: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  primaryOwner: PrimaryOwner$zodSchema.optional(),
  type: z.string().optional(),
});
