/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BaseApi = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

export const BaseApi$zodSchema: z.ZodType<BaseApi> = z.object({
  description: z.string().optional().describe(
    "API's description. A short description of your API.",
  ),
  id: z.string().optional().describe("API's uuid."),
  name: z.string().optional().describe(
    "API's name. Duplicate names can exists.",
  ),
});
