/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The origin of the API.
 */
export const BaseOriginContextOrigin$zodSchema = z.enum([
  "MANAGEMENT",
  "KUBERNETES",
  "INTEGRATION",
]).describe("The origin of the API.");

export type BaseOriginContextOrigin = z.infer<
  typeof BaseOriginContextOrigin$zodSchema
>;

export type BaseOriginContext = {
  origin?: BaseOriginContextOrigin | undefined;
};

export const BaseOriginContext$zodSchema: z.ZodType<
  BaseOriginContext,
  z.ZodTypeDef,
  unknown
> = z.object({
  origin: BaseOriginContextOrigin$zodSchema.optional(),
});
