/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CategoryApi, CategoryApi$zodSchema } from "./categoryapi.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of APIs within a Category
 */
export type CategoryApisResponse = {
  data?: Array<CategoryApi> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const CategoryApisResponse$zodSchema: z.ZodType<
  CategoryApisResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(CategoryApi$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of APIs within a Category");
