/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Operator, Operator$zodSchema } from "./operator.js";

/**
 * Selector type.
 */
export const ChannelSelectorType = {
  Http: "HTTP",
  Channel: "CHANNEL",
  Condition: "CONDITION",
  Mcp: "MCP",
} as const;
/**
 * Selector type.
 */
export type ChannelSelectorType = ClosedEnum<typeof ChannelSelectorType>;

export const ChannelSelectorType$zodSchema = z.enum([
  "HTTP",
  "CHANNEL",
  "CONDITION",
  "MCP",
]).describe("Selector type.");

/**
 * The operation associated with this channel selector.
 */
export const Operation = {
  Publish: "PUBLISH",
  Subscribe: "SUBSCRIBE",
} as const;
/**
 * The operation associated with this channel selector.
 */
export type Operation = ClosedEnum<typeof Operation>;

export const Operation$zodSchema = z.enum([
  "PUBLISH",
  "SUBSCRIBE",
]).describe("The operation associated with this channel selector.");

export type ChannelSelector = {
  type: ChannelSelectorType;
  operations?: Array<Operation> | undefined;
  channel?: string | undefined;
  channelOperator?: Operator | undefined;
  entrypoints?: Array<string> | undefined;
};

export const ChannelSelector$zodSchema: z.ZodType<ChannelSelector> = z.object({
  channel: z.string().default("/").describe("The channel of the selector"),
  channelOperator: Operator$zodSchema.default("STARTS_WITH").describe(
    "The path operator of the selector",
  ),
  entrypoints: z.array(z.string()).optional(),
  operations: z.array(Operation$zodSchema).optional().describe(
    "The list of operations associated with this channel selector.",
  ),
  type: ChannelSelectorType$zodSchema.describe("Selector type."),
});
