/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Plan, Plan$zodSchema } from "./plan.js";

export type CloseApiPlanRequest = {
  envId?: string | undefined;
  apiId: string;
  planId: string;
};

export const CloseApiPlanRequest$zodSchema: z.ZodType<
  CloseApiPlanRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  planId: z.string().describe("Id of a plan."),
});

export type CloseApiPlanResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Plan?: Plan | undefined;
  ErrorT?: ErrorT | undefined;
};

export const CloseApiPlanResponse$zodSchema: z.ZodType<
  CloseApiPlanResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  Plan: Plan$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
