/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of connector that emitted the metric
 */
export const ConnectorType = {
  Entrypoint: "entrypoint",
  Endpoint: "endpoint",
} as const;
/**
 * Type of connector that emitted the metric
 */
export type ConnectorType = ClosedEnum<typeof ConnectorType>;

export const ConnectorType$zodSchema = z.enum([
  "entrypoint",
  "endpoint",
]).describe("Type of connector that emitted the metric");
