/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ConsumerType, ConsumerType$zodSchema } from "./consumertype.js";

export type Consumer = {
  consumerType?: ConsumerType | undefined;
  consumerId?: string | undefined;
};

export const Consumer$zodSchema: z.ZodType<Consumer, z.ZodTypeDef, unknown> = z
  .object({
    consumerId: z.string().optional(),
    consumerType: ConsumerType$zodSchema.default("TAG"),
  });
