/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Cors = {
  allowCredentials?: boolean | undefined;
  allowHeaders?: Array<string> | undefined;
  allowMethods?: Array<string> | undefined;
  allowOrigin?: Array<string> | undefined;
  enabled?: boolean | undefined;
  exposeHeaders?: Array<string> | undefined;
  maxAge?: number | undefined;
  runPolicies?: boolean | undefined;
};

export const Cors$zodSchema: z.ZodType<Cors, z.ZodTypeDef, unknown> = z.object({
  allowCredentials: z.boolean().optional(),
  allowHeaders: z.array(z.string()).optional(),
  allowMethods: z.array(z.string()).optional(),
  allowOrigin: z.array(z.string()).optional(),
  enabled: z.boolean().optional(),
  exposeHeaders: z.array(z.string()).optional(),
  maxAge: z.number().int().default(-1),
  runPolicies: z.boolean().optional(),
});
