/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiV4Output, ApiV4Output$zodSchema } from "./apiv4output.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  ImportSwaggerDescriptor,
  ImportSwaggerDescriptor$zodSchema,
} from "./importswaggerdescriptor.js";

export type CreateApiFromSwaggerRequest = {
  envId?: string | undefined;
  ImportSwaggerDescriptor: ImportSwaggerDescriptor;
};

export const CreateApiFromSwaggerRequest$zodSchema: z.ZodType<
  CreateApiFromSwaggerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ImportSwaggerDescriptor: ImportSwaggerDescriptor$zodSchema,
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type CreateApiFromSwaggerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiV4?: ApiV4Output | undefined;
  ErrorT?: ErrorT | undefined;
};

export const CreateApiFromSwaggerResponse$zodSchema: z.ZodType<
  CreateApiFromSwaggerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiV4: ApiV4Output$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
