/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiV4Output, ApiV4Output$zodSchema } from "./apiv4output.js";
import { CreateApiV4, CreateApiV4$zodSchema } from "./createapiv4.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type CreateApiRequest = {
  envId?: string | undefined;
  CreateApiV4: CreateApiV4;
};

export const CreateApiRequest$zodSchema: z.ZodType<CreateApiRequest> = z.object(
  {
    CreateApiV4: CreateApiV4$zodSchema,
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  },
);

export type CreateApiResponse = ApiV4Output | ErrorT;

export const CreateApiResponse$zodSchema: z.ZodType<CreateApiResponse> = z
  .union([
    ApiV4Output$zodSchema,
    ErrorT$zodSchema,
  ]);
