/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateDocumentation,
  CreateDocumentation$zodSchema,
} from "./createdocumentation.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Page, Page$zodSchema } from "./page.js";

export type CreateDocumentationPageRequest = {
  envId?: string | undefined;
  apiId: string;
  CreateDocumentation: CreateDocumentation;
};

export const CreateDocumentationPageRequest$zodSchema: z.ZodType<
  CreateDocumentationPageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  CreateDocumentation: CreateDocumentation$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type CreateDocumentationPageResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Page?: Page | undefined;
  ErrorT?: ErrorT | undefined;
};

export const CreateDocumentationPageResponse$zodSchema: z.ZodType<
  CreateDocumentationPageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  Page: Page$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
