/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateSubscription,
  CreateSubscription$zodSchema,
} from "./createsubscription.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Subscription, Subscription$zodSchema } from "./subscription.js";

export type CreateApiSubscriptionRequest = {
  envId?: string | undefined;
  apiId: string;
  CreateSubscription: CreateSubscription;
};

export const CreateApiSubscriptionRequest$zodSchema: z.ZodType<
  CreateApiSubscriptionRequest
> = z.object({
  CreateSubscription: CreateSubscription$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type CreateApiSubscriptionResponse = Subscription | ErrorT;

export const CreateApiSubscriptionResponse$zodSchema: z.ZodType<
  CreateApiSubscriptionResponse
> = z.union([
  Subscription$zodSchema,
  ErrorT$zodSchema,
]);
