/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKeyMode, ApiKeyMode$zodSchema } from "./apikeymode.js";
import {
  SubscriptionConsumerConfiguration,
  SubscriptionConsumerConfiguration$zodSchema,
} from "./subscriptionconsumerconfiguration.js";

export type CreateSubscription = {
  applicationId: string;
  planId: string;
  customApiKey?: string | undefined;
  consumerConfiguration?: SubscriptionConsumerConfiguration | undefined;
  metadata?: { [k: string]: string } | undefined;
  apiKeyMode?: ApiKeyMode | undefined;
};

export const CreateSubscription$zodSchema: z.ZodType<
  CreateSubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyMode: ApiKeyMode$zodSchema.optional(),
  applicationId: z.string(),
  consumerConfiguration: SubscriptionConsumerConfiguration$zodSchema.optional(),
  customApiKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  planId: z.string(),
});
