/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { FlowV2, FlowV2$zodSchema } from "./flowv2.js";
import { PlanSecurity, PlanSecurity$zodSchema } from "./plansecurity.js";
import { PlanValidation, PlanValidation$zodSchema } from "./planvalidation.js";

export type CreatePlanV2 = {
  crossId?: string | undefined;
  characteristics?: Array<string> | undefined;
  commentMessage?: string | undefined;
  commentRequired?: boolean | undefined;
  definitionVersion: DefinitionVersion;
  description?: string | undefined;
  excludedGroups?: Array<string> | undefined;
  generalConditions?: string | undefined;
  name?: string | undefined;
  order?: number | undefined;
  security?: PlanSecurity | undefined;
  selectionRule?: string | undefined;
  tags?: Array<string> | undefined;
  validation?: PlanValidation | undefined;
  flows?: Array<FlowV2> | undefined;
};

export const CreatePlanV2$zodSchema: z.ZodType<
  CreatePlanV2,
  z.ZodTypeDef,
  unknown
> = z.object({
  characteristics: z.array(z.string()).optional(),
  commentMessage: z.string().optional(),
  commentRequired: z.boolean().optional(),
  crossId: z.string().optional(),
  definitionVersion: DefinitionVersion$zodSchema,
  description: z.string().optional(),
  excludedGroups: z.array(z.string()).optional(),
  flows: z.array(FlowV2$zodSchema).optional(),
  generalConditions: z.string().optional(),
  name: z.string().optional(),
  order: z.number().int().optional(),
  security: PlanSecurity$zodSchema.optional(),
  selectionRule: z.string().optional(),
  tags: z.array(z.string()).optional(),
  validation: PlanValidation$zodSchema.optional(),
});
