/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AccessControl, AccessControl$zodSchema } from "./accesscontrol.js";
import { Visibility, Visibility$zodSchema } from "./visibility.js";

/**
 * The type of the page.
 */
export const CreateDocumentationType$zodSchema = z.enum([
  "MARKDOWN",
  "FOLDER",
  "SWAGGER",
  "ASYNCAPI",
  "ASCIIDOC",
]).describe("The type of the page.");

export type CreateDocumentationType = z.infer<
  typeof CreateDocumentationType$zodSchema
>;

export type CreateDocumentation = {
  name: string;
  type: CreateDocumentationType;
  visibility?: Visibility | undefined;
  parentId?: string | undefined;
  excludedAccessControls?: boolean | undefined;
  accessControls?: Array<AccessControl> | undefined;
};

export const CreateDocumentation$zodSchema: z.ZodType<
  CreateDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessControls: z.array(AccessControl$zodSchema).optional(),
  excludedAccessControls: z.boolean().optional(),
  name: z.string(),
  parentId: z.string().optional(),
  type: CreateDocumentationType$zodSchema,
  visibility: Visibility$zodSchema.optional(),
});
