/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKeyMode, ApiKeyMode$zodSchema } from "./apikeymode.js";
import {
  SubscriptionConsumerConfiguration,
  SubscriptionConsumerConfiguration$zodSchema,
} from "./subscriptionconsumerconfiguration.js";

export type CreateSubscription = {
  applicationId: string;
  planId: string;
  customApiKey?: string | undefined;
  consumerConfiguration?: SubscriptionConsumerConfiguration | undefined;
  metadata?: { [k: string]: string } | undefined;
  apiKeyMode?: ApiKeyMode | undefined;
};

export const CreateSubscription$zodSchema: z.ZodType<CreateSubscription> = z
  .object({
    apiKeyMode: ApiKeyMode$zodSchema.optional().describe(
      "The mode of an application regarding ApiKey plans.\n* UNSPECIFIED: no selected mode yet\n* EXCLUSIVE: an API Key is generated for each new subscription\n* SHARED: reuse always the same API Key for all subscriptions\n",
    ),
    applicationId: z.string().describe(
      "The id of the application subscribing.",
    ),
    consumerConfiguration: SubscriptionConsumerConfiguration$zodSchema
      .optional().describe(
        "Consumer configuration associated to the subscription in case it is attached to a push plan.",
      ),
    customApiKey: z.string().optional().describe(
      "Optional custom API Key that can be given when the subscription is related to an api-key plan and custom API Key support is enabled.",
    ),
    metadata: z.record(z.string(), z.string()).optional().describe(
      "A list of metadata associated to this subscription.",
    ),
    planId: z.string().describe(
      "The id plan the application is subscribing to.",
    ),
  });
