/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DebugEvent, DebugEvent$zodSchema } from "./debugevent.js";
import {
  DebugHttpRequest,
  DebugHttpRequest$zodSchema,
} from "./debughttprequest.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type DebugApiRequest = {
  envId?: string | undefined;
  apiId: string;
  DebugHttpRequest: DebugHttpRequest;
};

export const DebugApiRequest$zodSchema: z.ZodType<DebugApiRequest> = z.object({
  DebugHttpRequest: DebugHttpRequest$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type DebugApiResponse = DebugEvent | ErrorT;

export const DebugApiResponse$zodSchema: z.ZodType<DebugApiResponse> = z.union([
  DebugEvent$zodSchema,
  ErrorT$zodSchema,
]);
