/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DebugHttpRequest = {
  path?: string | undefined;
  method?: string | undefined;
  body?: string | undefined;
  headers?: { [k: string]: Array<string> } | undefined;
};

export const DebugHttpRequest$zodSchema: z.ZodType<DebugHttpRequest> = z.object(
  {
    body: z.string().optional().describe("The body of the request."),
    headers: z.record(z.string(), z.array(z.string())).optional().describe(
      "The headers of the request.",
    ),
    method: z.string().optional().describe("The HTTP method of the request."),
    path: z.string().optional().describe("The path of the request."),
  },
);
