/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeletedIngestedApisResponse,
  DeletedIngestedApisResponse$zodSchema,
} from "./deletedingestedapisresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type DeleteIngestedApisRequest = {
  envId?: string | undefined;
  integrationId: string;
};

export const DeleteIngestedApisRequest$zodSchema: z.ZodType<
  DeleteIngestedApisRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  integrationId: z.string().describe("Id of an integration."),
});

export type DeleteIngestedApisResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  DeletedIngestedApisResponse?: DeletedIngestedApisResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const DeleteIngestedApisResponse$zodSchema: z.ZodType<
  DeleteIngestedApisResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  DeletedIngestedApisResponse: DeletedIngestedApisResponse$zodSchema.optional(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
