/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type DeleteApiPictureRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const DeleteApiPictureRequest$zodSchema: z.ZodType<
  DeleteApiPictureRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type DeleteApiPictureResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorT?: ErrorT | undefined;
};

export const DeleteApiPictureResponse$zodSchema: z.ZodType<
  DeleteApiPictureResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
