/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeletedIngestedApisResponse,
  DeletedIngestedApisResponse$zodSchema,
} from "./deletedingestedapisresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type DeleteIngestedApisRequest = {
  envId?: string | undefined;
  integrationId: string;
};

export const DeleteIngestedApisRequest$zodSchema: z.ZodType<
  DeleteIngestedApisRequest
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  integrationId: z.string().describe("Id of an integration."),
});

export type DeleteIngestedApisResponse = DeletedIngestedApisResponse | ErrorT;

export const DeleteIngestedApisResponse$zodSchema: z.ZodType<
  DeleteIngestedApisResponse
> = z.union([
  DeletedIngestedApisResponse$zodSchema,
  ErrorT$zodSchema,
]);
