/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const FilteredField$zodSchema = z.enum([
  "GROUPS",
  "PLANS",
  "MEMBERS",
  "PAGES",
]);

export type FilteredField = z.infer<typeof FilteredField$zodSchema>;

export type DuplicateApiOptions = {
  contextPath?: string | undefined;
  host?: string | undefined;
  version?: string | undefined;
  filteredFields: Array<FilteredField>;
};

export const DuplicateApiOptions$zodSchema: z.ZodType<
  DuplicateApiOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  contextPath: z.string().optional(),
  filteredFields: z.array(FilteredField$zodSchema),
  host: z.string().optional(),
  version: z.string().optional(),
});
