/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FilteredField = {
  Groups: "GROUPS",
  Plans: "PLANS",
  Members: "MEMBERS",
  Pages: "PAGES",
} as const;
export type FilteredField = ClosedEnum<typeof FilteredField>;

export const FilteredField$zodSchema = z.enum([
  "GROUPS",
  "PLANS",
  "MEMBERS",
  "PAGES",
]);

export type DuplicateApiOptions = {
  contextPath?: string | undefined;
  host?: string | undefined;
  version?: string | undefined;
  filteredFields: Array<FilteredField>;
};

export const DuplicateApiOptions$zodSchema: z.ZodType<DuplicateApiOptions> = z
  .object({
    contextPath: z.string().optional().describe(
      "The context path of the duplicated API (required for HTTP APIs).",
    ),
    filteredFields: z.array(FilteredField$zodSchema).describe(
      "The list of API fields that can be excluded to create the new API.",
    ),
    host: z.string().optional().describe(
      "The host of the duplicated API (required for TCP APIs).",
    ),
    version: z.string().optional().describe(
      "The version of the duplicated API. If it is not defined, the value of the source API is used.",
    ),
  });
