/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DynamicPropertyProvider,
  DynamicPropertyProvider$zodSchema,
} from "./dynamicpropertyprovider.js";
import {
  HttpDynamicPropertyProviderConfiguration,
  HttpDynamicPropertyProviderConfiguration$zodSchema,
} from "./httpdynamicpropertyproviderconfiguration.js";

export type Configuration = HttpDynamicPropertyProviderConfiguration;

export const Configuration$zodSchema: z.ZodType<Configuration> =
  HttpDynamicPropertyProviderConfiguration$zodSchema;

export type DynamicPropertyService = {
  schedule?: string | undefined;
  provider?: DynamicPropertyProvider | undefined;
  configuration?: HttpDynamicPropertyProviderConfiguration | undefined;
  enabled?: boolean | undefined;
};

export const DynamicPropertyService$zodSchema: z.ZodType<
  DynamicPropertyService
> = z.object({
  configuration: HttpDynamicPropertyProviderConfiguration$zodSchema.optional(),
  enabled: z.boolean().default(true).describe("Is the service enabled or not."),
  provider: DynamicPropertyProvider$zodSchema.optional().describe(
    "The type of the dynamic property provider.",
  ),
  schedule: z.string().optional().describe("The schedule of the service"),
});
