/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  HealthCheckStep,
  HealthCheckStep$zodSchema,
} from "./healthcheckstep.js";

export type EndpointHealthCheckService = {
  schedule?: string | undefined;
  steps?: Array<HealthCheckStep> | undefined;
  enabled?: boolean | undefined;
  inherit?: boolean | undefined;
};

export const EndpointHealthCheckService$zodSchema: z.ZodType<
  EndpointHealthCheckService,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean().optional(),
  inherit: z.boolean().optional(),
  schedule: z.string().optional(),
  steps: z.array(HealthCheckStep$zodSchema).optional(),
});
