/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ServiceV4, ServiceV4$zodSchema } from "./servicev4.js";

export type EndpointGroupServices = {
  discovery?: ServiceV4 | undefined;
  healthCheck?: ServiceV4 | undefined;
};

export const EndpointGroupServices$zodSchema: z.ZodType<
  EndpointGroupServices,
  z.ZodTypeDef,
  unknown
> = z.object({
  discovery: ServiceV4$zodSchema.optional(),
  healthCheck: ServiceV4$zodSchema.optional(),
});
