/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ServiceV4, ServiceV4$zodSchema } from "./servicev4.js";

export type EndpointServices = { healthCheck?: ServiceV4 | undefined };

export const EndpointServices$zodSchema: z.ZodType<
  EndpointServices,
  z.ZodTypeDef,
  unknown
> = z.object({
  healthCheck: ServiceV4$zodSchema.optional(),
});
