/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The configuration of the service
 */
export type EndpointDiscoveryServiceConfiguration = {};

export const EndpointDiscoveryServiceConfiguration$zodSchema: z.ZodType<
  EndpointDiscoveryServiceConfiguration
> = z.object({}).describe("The configuration of the service");

export type EndpointDiscoveryService = {
  provider?: string | undefined;
  configuration?: EndpointDiscoveryServiceConfiguration | undefined;
  enabled?: boolean | undefined;
};

export const EndpointDiscoveryService$zodSchema: z.ZodType<
  EndpointDiscoveryService
> = z.object({
  configuration: z.lazy(() => EndpointDiscoveryServiceConfiguration$zodSchema)
    .optional().describe("The configuration of the service"),
  enabled: z.boolean().default(true).describe("Is the service enabled or not."),
  provider: z.string().optional().describe("The provider of the service"),
});
