/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Dlq, Dlq$zodSchema } from "./dlq.js";
import { Qos, Qos$zodSchema } from "./qos.js";

export type EntrypointConfiguration = {};

export const EntrypointConfiguration$zodSchema: z.ZodType<
  EntrypointConfiguration
> = z.object({});

export type Entrypoint = {
  type: string;
  qos?: Qos | undefined;
  dlq?: Dlq | undefined;
  configuration?: EntrypointConfiguration | undefined;
};

export const Entrypoint$zodSchema: z.ZodType<Entrypoint> = z.object({
  configuration: z.lazy(() => EntrypointConfiguration$zodSchema).optional(),
  dlq: Dlq$zodSchema.optional(),
  qos: Qos$zodSchema.default("AUTO").describe(
    "Type of the quality of service.",
  ),
  type: z.string().describe("The type of the entrypoint"),
});
