/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Detail = {
  message?: string | undefined;
  location?: string | undefined;
  invalidValue?: any | undefined;
};

export const Detail$zodSchema: z.ZodType<Detail> = z.object({
  invalidValue: z.any().optional().describe("The invalid value."),
  location: z.string().optional().describe(
    "The json path of the field in error.",
  ),
  message: z.string().optional().describe("The error message"),
});

/**
 * Generic error response
 */
export type ErrorT = {
  httpStatus?: number | undefined;
  message?: string | undefined;
  technicalCode?: string | undefined;
  parameters?: { [k: string]: string } | undefined;
  details?: Array<Detail> | undefined;
};

export const ErrorT$zodSchema: z.ZodType<ErrorT> = z.object({
  details: z.array(z.lazy(() => Detail$zodSchema)).optional().describe(
    "A list of details about the error",
  ),
  httpStatus: z.int().optional().describe("The error code"),
  message: z.string().optional().describe("The error message"),
  parameters: z.record(z.string(), z.string()).optional().describe(
    "A map of parameters to be used in the error message",
  ),
  technicalCode: z.string().optional().describe(
    "A technical code to identify the error",
  ),
}).describe("Generic error response");
