/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Event, Event$zodSchema } from "./event.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of Event
 */
export type EventsResponse = {
  data?: Array<Event> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const EventsResponse$zodSchema: z.ZodType<
  EventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Event$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of Event");
