/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BaseUser, BaseUser$zodSchema } from "./baseuser.js";
import { EventType, EventType$zodSchema } from "./eventtype.js";

export type Event = {
  id?: string | undefined;
  createdAt?: string | undefined;
  environmentIds?: Array<string> | undefined;
  initiator?: BaseUser | undefined;
  type?: EventType | undefined;
  payload?: string | undefined;
  properties?: { [k: string]: string } | undefined;
};

export const Event$zodSchema: z.ZodType<Event> = z.object({
  createdAt: z.iso.datetime({ offset: true }).optional().describe(
    "The date when the event has been created.",
  ),
  environmentIds: z.array(z.string()).optional().describe(
    "The id of the environments.",
  ),
  id: z.string().optional().describe("The internal UUID of the event."),
  initiator: BaseUser$zodSchema.optional().describe(
    "Base information about a user.",
  ),
  payload: z.string().optional().describe("The event payload."),
  properties: z.record(z.string(), z.string()).optional().describe(
    "Properties of the event.",
  ),
  type: EventType$zodSchema.optional().describe("The type of the event."),
});
