/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type ExportApiSubscriptionsRequest = {
  envId?: string | undefined;
  apiId: string;
  applicationIds?: Array<string> | undefined;
  planIds?: Array<string> | undefined;
  statuses?: Array<SubscriptionStatus> | undefined;
  apiKey?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const ExportApiSubscriptionsRequest$zodSchema: z.ZodType<
  ExportApiSubscriptionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  apiKey: z.string().describe(
    "API Key associated to the subscription to filter on.",
  ).optional(),
  applicationIds: z.array(z.string()).describe(
    "List of application ids to filter on.",
  ).optional(),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
  planIds: z.array(z.string()).describe("List of plan ids to filter on.")
    .optional(),
  statuses: z.array(SubscriptionStatus$zodSchema).describe(
    "List of status filters.",
  ).optional(),
});

export type ExportApiSubscriptionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorT?: ErrorT | undefined;
  Headers: { [k: string]: Array<string> };
};

export const ExportApiSubscriptionsResponse$zodSchema: z.ZodType<
  ExportApiSubscriptionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  Headers: z.record(z.array(z.string())),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
