/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  ExportApiV4Output,
  ExportApiV4Output$zodSchema,
} from "./exportapiv4input.js";

export const ExcludeAdditionalDatum = {
  Groups: "groups",
  Members: "members",
  Metadata: "metadata",
  Pages: "pages",
  Plans: "plans",
} as const;
export type ExcludeAdditionalDatum = ClosedEnum<typeof ExcludeAdditionalDatum>;

export const ExcludeAdditionalDatum$zodSchema = z.enum([
  "groups",
  "members",
  "metadata",
  "pages",
  "plans",
]);

export type ExportApiDefinitionRequest = {
  envId?: string | undefined;
  apiId: string;
  excludeAdditionalData?: Array<ExcludeAdditionalDatum> | undefined;
};

export const ExportApiDefinitionRequest$zodSchema: z.ZodType<
  ExportApiDefinitionRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  excludeAdditionalData: z.array(ExcludeAdditionalDatum$zodSchema).describe(
    "Exclude additional data from the API definition export",
  ).optional(),
});

export type ExportApiDefinitionResponseResult = ExportApiV4Output | ErrorT;

export const ExportApiDefinitionResponseResult$zodSchema: z.ZodType<
  ExportApiDefinitionResponseResult
> = z.union([
  ExportApiV4Output$zodSchema,
  ErrorT$zodSchema,
]);

export type ExportApiDefinitionResponse = {
  Headers: { [k: string]: Array<string> };
  Result: ExportApiV4Output | ErrorT;
};

export const ExportApiDefinitionResponse$zodSchema: z.ZodType<
  ExportApiDefinitionResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: z.union([
    ExportApiV4Output$zodSchema,
    ErrorT$zodSchema,
  ]),
});
