/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * newt AI feedback request id.
 */
export type FeedbackRequestId = {
  chatId?: string | undefined;
  userMessageId?: string | undefined;
  agentMessageId?: string | undefined;
};

export const FeedbackRequestId$zodSchema: z.ZodType<FeedbackRequestId> = z
  .object({
    agentMessageId: z.string().optional(),
    chatId: z.string().optional(),
    userMessageId: z.string().optional(),
  }).describe("newt AI feedback request id.");
