/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ExpressionLanguageFeedback,
  ExpressionLanguageFeedback$zodSchema,
} from "./expressionlanguagefeedback.js";

export type FeedbackElRequest = {
  envId?: string | undefined;
  apiId: string;
  ExpressionLanguageFeedback: ExpressionLanguageFeedback;
};

export const FeedbackElRequest$zodSchema: z.ZodType<FeedbackElRequest> = z
  .object({
    ExpressionLanguageFeedback: ExpressionLanguageFeedback$zodSchema,
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  });
