/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The stage of the flow.
 */
export const FlowStage$zodSchema = z.enum([
  "PLATFORM",
  "PLAN",
  "API",
]).describe("The stage of the flow.");

export type FlowStage = z.infer<typeof FlowStage$zodSchema>;
