/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FeedbackRequestId,
  FeedbackRequestId$zodSchema,
} from "./feedbackrequestid.js";

/**
 * Response an expression language generation
 */
export type GenerateExpressionLanguageResponse = {
  message?: string | undefined;
  feedbackRequestId?: FeedbackRequestId | undefined;
};

export const GenerateExpressionLanguageResponse$zodSchema: z.ZodType<
  GenerateExpressionLanguageResponse
> = z.object({
  feedbackRequestId: FeedbackRequestId$zodSchema.optional().describe(
    "newt AI feedback request id.",
  ),
  message: z.string().optional().describe("Expression language generated."),
}).describe("Response an expression language generation");
