/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiScoring, ApiScoring$zodSchema } from "./apiscoring.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiScoringRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetApiScoringRequest$zodSchema: z.ZodType<
  GetApiScoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type GetApiScoringResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiScoring?: ApiScoring | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiScoringResponse$zodSchema: z.ZodType<
  GetApiScoringResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiScoring: ApiScoring$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
