/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  SubscribersResponse,
  SubscribersResponse$zodSchema,
} from "./subscribersresponse.js";

export type GetApiSubscribersRequest = {
  envId?: string | undefined;
  apiId: string;
  name?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const GetApiSubscribersRequest$zodSchema: z.ZodType<
  GetApiSubscribersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  name: z.string().describe(
    "Name to use to filter subscribers. <br>\n"
      + "Can be a part of a name. <br>\n"
      + "For example, `foo` will match `foo`, `foobar` and `barfoo`.",
  ).optional(),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
});

export type GetApiSubscribersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  SubscribersResponse?: SubscribersResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiSubscribersResponse$zodSchema: z.ZodType<
  GetApiSubscribersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  SubscribersResponse: SubscribersResponse$zodSchema.optional(),
});
