/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiMessageLogsResponse,
  ApiMessageLogsResponse$zodSchema,
} from "./apimessagelogsresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiMessageLogsRequest = {
  envId?: string | undefined;
  apiId: string;
  requestId: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const GetApiMessageLogsRequest$zodSchema: z.ZodType<
  GetApiMessageLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
  requestId: z.string().describe("Id of a request."),
});

export type GetApiMessageLogsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiMessageLogsResponse?: ApiMessageLogsResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiMessageLogsResponse$zodSchema: z.ZodType<
  GetApiMessageLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiMessageLogsResponse: ApiMessageLogsResponse$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
