/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiAggregatedMessageLogsResponse,
  ApiAggregatedMessageLogsResponse$zodSchema,
} from "./apiaggregatedmessagelogsresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiAggregatedMessageLogsRequest = {
  envId?: string | undefined;
  apiId: string;
  requestId: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const GetApiAggregatedMessageLogsRequest$zodSchema: z.ZodType<
  GetApiAggregatedMessageLogsRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.int().default(1).describe("The page number for pagination."),
  perPage: z.int().default(10).describe(
    "The number of items per page for pagination.\n",
  ),
  requestId: z.string().describe("Id of a request."),
});

export type GetApiAggregatedMessageLogsResponse =
  | ApiAggregatedMessageLogsResponse
  | ErrorT;

export const GetApiAggregatedMessageLogsResponse$zodSchema: z.ZodType<
  GetApiAggregatedMessageLogsResponse
> = z.union([
  ApiAggregatedMessageLogsResponse$zodSchema,
  ErrorT$zodSchema,
]);
