/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Plan, Plan$zodSchema } from "./plan.js";

export type GetApiPlanRequest = {
  envId?: string | undefined;
  apiId: string;
  planId: string;
};

export const GetApiPlanRequest$zodSchema: z.ZodType<GetApiPlanRequest> = z
  .object({
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
    planId: z.string().describe("Id of a plan."),
  });

export type GetApiPlanResponseResult = Plan | ErrorT;

export const GetApiPlanResponseResult$zodSchema: z.ZodType<
  GetApiPlanResponseResult
> = z.union([
  Plan$zodSchema,
  ErrorT$zodSchema,
]);

export type GetApiPlanResponse = {
  Headers: { [k: string]: Array<string> };
  Result: Plan | ErrorT;
};

export const GetApiPlanResponse$zodSchema: z.ZodType<GetApiPlanResponse> = z
  .object({
    Headers: z.record(z.string(), z.array(z.string())).default({}),
    Result: z.union([
      Plan$zodSchema,
      ErrorT$zodSchema,
    ]),
  });
