/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiProductInfo, ApiProductInfo$zodSchema } from "./apiproductinfo.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiProductsForApiRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetApiProductsForApiRequest$zodSchema: z.ZodType<
  GetApiProductsForApiRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

/**
 * List of API Products that include this API
 */
export type GetApiProductsForApiResponseBody = {
  data?: Array<ApiProductInfo> | undefined;
};

export const GetApiProductsForApiResponseBody$zodSchema: z.ZodType<
  GetApiProductsForApiResponseBody
> = z.object({
  data: z.array(ApiProductInfo$zodSchema).optional(),
}).describe("List of API Products that include this API");

export type GetApiProductsForApiResponse =
  | GetApiProductsForApiResponseBody
  | ErrorT;

export const GetApiProductsForApiResponse$zodSchema: z.ZodType<
  GetApiProductsForApiResponse
> = z.union([
  z.lazy(() => GetApiProductsForApiResponseBody$zodSchema),
  ErrorT$zodSchema,
]);
