/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiBackgroundRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetApiBackgroundRequest$zodSchema: z.ZodType<
  GetApiBackgroundRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type GetApiBackgroundResponse = Uint8Array | string | ErrorT;

export const GetApiBackgroundResponse$zodSchema: z.ZodType<
  GetApiBackgroundResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  ErrorT$zodSchema,
]);
