/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiHealthAvailabilityResponse,
  ApiHealthAvailabilityResponse$zodSchema,
} from "./apihealthavailabilityresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { HealthField, HealthField$zodSchema } from "./healthfield.js";

export type GetApiAvailabilityRequest = {
  envId?: string | undefined;
  apiId: string;
  field?: HealthField | undefined;
};

export const GetApiAvailabilityRequest$zodSchema: z.ZodType<
  GetApiAvailabilityRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  field: HealthField$zodSchema.default("endpoint"),
});

export type GetApiAvailabilityResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiHealthAvailabilityResponse?: ApiHealthAvailabilityResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiAvailabilityResponse$zodSchema: z.ZodType<
  GetApiAvailabilityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiHealthAvailabilityResponse: ApiHealthAvailabilityResponse$zodSchema
    .optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
