/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiScoring, ApiScoring$zodSchema } from "./apiscoring.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiScoringRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetApiScoringRequest$zodSchema: z.ZodType<GetApiScoringRequest> = z
  .object({
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  });

export type GetApiScoringResponse = ApiScoring | ErrorT;

export const GetApiScoringResponse$zodSchema: z.ZodType<GetApiScoringResponse> =
  z.union([
    ApiScoring$zodSchema,
    ErrorT$zodSchema,
  ]);
