/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiLogResponse, ApiLogResponse$zodSchema } from "./apilogresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiLogRequest = {
  envId?: string | undefined;
  apiId: string;
  requestId: string;
};

export const GetApiLogRequest$zodSchema: z.ZodType<GetApiLogRequest> = z.object(
  {
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
    requestId: z.string().describe("Id of a request."),
  },
);

export type GetApiLogResponse = ApiLogResponse | ErrorT;

export const GetApiLogResponse$zodSchema: z.ZodType<GetApiLogResponse> = z
  .union([
    ApiLogResponse$zodSchema,
    ErrorT$zodSchema,
  ]);
