/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Event, Event$zodSchema } from "./event.js";

export type GetApiEventByIdRequest = {
  envId?: string | undefined;
  apiId: string;
  eventId: string;
};

export const GetApiEventByIdRequest$zodSchema: z.ZodType<
  GetApiEventByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  eventId: z.string().describe("Id of an API Event."),
});

export type GetApiEventByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Event?: Event | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiEventByIdResponse$zodSchema: z.ZodType<
  GetApiEventByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  Event: Event$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
