/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiDocumentationPagesResponse,
  ApiDocumentationPagesResponse$zodSchema,
} from "./apidocumentationpagesresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiPagesRequest = {
  envId?: string | undefined;
  apiId: string;
  parentId?: string | undefined;
};

export const GetApiPagesRequest$zodSchema: z.ZodType<
  GetApiPagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  parentId: z.string().describe(
    "Id of the parent folder or 'ROOT' for the top folder.",
  ).optional(),
});

export type GetApiPagesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiDocumentationPagesResponse?: ApiDocumentationPagesResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiPagesResponse$zodSchema: z.ZodType<
  GetApiPagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiDocumentationPagesResponse: ApiDocumentationPagesResponse$zodSchema
    .optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
