/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiAnalyticsRequestsCountResponse,
  ApiAnalyticsRequestsCountResponse$zodSchema,
} from "./apianalyticsrequestscountresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiAnalyticsRequestCountRequest = {
  envId?: string | undefined;
  apiId: string;
  from?: number | undefined;
  to?: number | undefined;
};

export const GetApiAnalyticsRequestCountRequest$zodSchema: z.ZodType<
  GetApiAnalyticsRequestCountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  from: z.number().int().describe(
    "The timestamp from which the logs will be returned.\n"
      + "",
  ).optional(),
  to: z.number().int().describe(
    "The timestamp to which the logs will be returned.\n"
      + "",
  ).optional(),
});

export type GetApiAnalyticsRequestCountResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiAnalyticsRequestsCountResponse?:
    | ApiAnalyticsRequestsCountResponse
    | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetApiAnalyticsRequestCountResponse$zodSchema: z.ZodType<
  GetApiAnalyticsRequestCountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiAnalyticsRequestsCountResponse: ApiAnalyticsRequestsCountResponse$zodSchema
    .optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
