/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiHealthLogsResponse,
  ApiHealthLogsResponse$zodSchema,
} from "./apihealthlogsresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetApiHealthLogsRequest = {
  envId?: string | undefined;
  apiId: string;
  from?: number | undefined;
  to?: number | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
  success?: boolean | undefined;
};

export const GetApiHealthLogsRequest$zodSchema: z.ZodType<
  GetApiHealthLogsRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  from: z.int().describe(
    "The timestamp from which the logs will be returned.\n",
  ).optional(),
  to: z.int().describe("The timestamp to which the logs will be returned.\n")
    .optional(),
  page: z.int().default(1).describe("The page number for pagination.")
    .optional(),
  perPage: z.int().default(10).describe(
    "The number of items per page for pagination.\n",
  ).optional(),
  success: z.boolean().describe("Filter logs by success status").optional(),
});

export type GetApiHealthLogsResponse = ApiHealthLogsResponse | ErrorT;

export const GetApiHealthLogsResponse$zodSchema: z.ZodType<
  GetApiHealthLogsResponse
> = z.union([
  ApiHealthLogsResponse$zodSchema,
  ErrorT$zodSchema,
]);
