/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetCurrentApiDeploymentRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetCurrentApiDeploymentRequest$zodSchema: z.ZodType<
  GetCurrentApiDeploymentRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

/**
 * Current API deployment found
 */
export type GetCurrentApiDeploymentResponseBody = {};

export const GetCurrentApiDeploymentResponseBody$zodSchema: z.ZodType<
  GetCurrentApiDeploymentResponseBody
> = z.object({}).describe("Current API deployment found");

export type GetCurrentApiDeploymentResponse =
  | GetCurrentApiDeploymentResponseBody
  | ErrorT;

export const GetCurrentApiDeploymentResponse$zodSchema: z.ZodType<
  GetCurrentApiDeploymentResponse
> = z.union([
  z.lazy(() => GetCurrentApiDeploymentResponseBody$zodSchema),
  ErrorT$zodSchema,
]);
