/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CategoryApisResponse,
  CategoryApisResponse$zodSchema,
} from "./categoryapisresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetCategoryApisPageRequest = {
  envId?: string | undefined;
  categoryIdOrKey: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const GetCategoryApisPageRequest$zodSchema: z.ZodType<
  GetCategoryApisPageRequest
> = z.object({
  categoryIdOrKey: z.string().describe("Id or Key of a category."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.int().default(1).describe("The page number for pagination."),
  perPage: z.int().default(10).describe(
    "The number of items per page for pagination.\n",
  ),
});

export type GetCategoryApisPageResponse = CategoryApisResponse | ErrorT;

export const GetCategoryApisPageResponse$zodSchema: z.ZodType<
  GetCategoryApisPageResponse
> = z.union([
  CategoryApisResponse$zodSchema,
  ErrorT$zodSchema,
]);
