/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Integration, Integration$zodSchema } from "./integration.js";

export type GetIntegrationRequest = {
  envId?: string | undefined;
  integrationId: string;
};

export const GetIntegrationRequest$zodSchema: z.ZodType<GetIntegrationRequest> =
  z.object({
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
    integrationId: z.string().describe("Id of an integration."),
  });

export type GetIntegrationResponse = Integration | ErrorT;

export const GetIntegrationResponse$zodSchema: z.ZodType<
  GetIntegrationResponse
> = z.union([
  Integration$zodSchema,
  ErrorT$zodSchema,
]);
