/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  NativeApiLogsResponse,
  NativeApiLogsResponse$zodSchema,
} from "./nativeapilogsresponse.js";

export const GetNativeApiLogsConnectionStatus = {
  Connected: "CONNECTED",
  ConnectionError: "CONNECTION_ERROR",
  SessionError: "SESSION_ERROR",
  InternalError: "INTERNAL_ERROR",
} as const;
export type GetNativeApiLogsConnectionStatus = ClosedEnum<
  typeof GetNativeApiLogsConnectionStatus
>;

export const GetNativeApiLogsConnectionStatus$zodSchema = z.enum([
  "CONNECTED",
  "CONNECTION_ERROR",
  "SESSION_ERROR",
  "INTERNAL_ERROR",
]);

export type GetNativeApiLogsRequest = {
  envId?: string | undefined;
  apiId: string;
  page?: number | undefined;
  perPage?: number | undefined;
  from: number;
  to: number;
  applicationIds?: Array<string> | undefined;
  planIds?: Array<string> | undefined;
  connectionStatuses?: Array<GetNativeApiLogsConnectionStatus> | undefined;
};

export const GetNativeApiLogsRequest$zodSchema: z.ZodType<
  GetNativeApiLogsRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  applicationIds: z.array(z.string()).describe(
    "List of application ids to filter on.",
  ).optional(),
  connectionStatuses: z.array(GetNativeApiLogsConnectionStatus$zodSchema)
    .describe("Filter by native connection status.").optional(),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  from: z.int().describe("The timestamp from which the logs will be returned."),
  page: z.int().default(1).describe("The page number for pagination."),
  perPage: z.int().default(10).describe(
    "The number of items per page for pagination.\n",
  ),
  planIds: z.array(z.string()).describe("List of plan ids to filter on.")
    .optional(),
  to: z.int().describe("The timestamp to which the logs will be returned."),
});

export type GetNativeApiLogsResponse = NativeApiLogsResponse | ErrorT;

export const GetNativeApiLogsResponse$zodSchema: z.ZodType<
  GetNativeApiLogsResponse
> = z.union([
  NativeApiLogsResponse$zodSchema,
  ErrorT$zodSchema,
]);
