/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiAnalyticsOverPeriodResponse,
  ApiAnalyticsOverPeriodResponse$zodSchema,
} from "./apianalyticsoverperiodresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetResponseTimeOverTimeRequest = {
  envId?: string | undefined;
  apiId: string;
  from?: number | undefined;
  to?: number | undefined;
};

export const GetResponseTimeOverTimeRequest$zodSchema: z.ZodType<
  GetResponseTimeOverTimeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  from: z.number().int().describe(
    "The timestamp from which the logs will be returned.\n"
      + "",
  ).optional(),
  to: z.number().int().describe(
    "The timestamp to which the logs will be returned.\n"
      + "",
  ).optional(),
});

export type GetResponseTimeOverTimeResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiAnalyticsOverPeriodResponse?: ApiAnalyticsOverPeriodResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetResponseTimeOverTimeResponse$zodSchema: z.ZodType<
  GetResponseTimeOverTimeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiAnalyticsOverPeriodResponse: ApiAnalyticsOverPeriodResponse$zodSchema
    .optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
