/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiSpecGenRequestState,
  ApiSpecGenRequestState$zodSchema,
} from "./apispecgenrequeststate.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type GetSpecGenStateRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const GetSpecGenStateRequest$zodSchema: z.ZodType<
  GetSpecGenStateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type GetSpecGenStateResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiSpecGenRequestState?: ApiSpecGenRequestState | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetSpecGenStateResponse$zodSchema: z.ZodType<
  GetSpecGenStateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiSpecGenRequestState: ApiSpecGenRequestState$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
