/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GroupSearchParams = { ids?: Array<string> | undefined };

export const GroupSearchParams$zodSchema: z.ZodType<GroupSearchParams> = z
  .object({
    ids: z.array(z.string()).optional().describe(
      "List of group IDs to search for.",
    ),
  });
