/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Group, Group$zodSchema } from "./group.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import {
  ResponseMetadata,
  ResponseMetadata$zodSchema,
} from "./responsemetadata.js";

/**
 * Page of Groups
 */
export type GroupsResponse = {
  data?: Array<Group> | undefined;
  links?: Links | undefined;
  metadata?: ResponseMetadata | undefined;
  pagination?: Pagination | undefined;
};

export const GroupsResponse$zodSchema: z.ZodType<
  GroupsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Group$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  metadata: ResponseMetadata$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of Groups");
