/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A health check request
 */
export type HealthCheckLogRequest = {
  uri?: string | undefined;
  method?: string | undefined;
  headers?: { [k: string]: string } | undefined;
};

export const HealthCheckLogRequest$zodSchema: z.ZodType<HealthCheckLogRequest> =
  z.object({
    headers: z.record(z.string(), z.string()).optional().describe(
      "The request headers",
    ),
    method: z.string().optional().describe("The http method"),
    uri: z.string().optional().describe("The uri called"),
  }).describe("A health check request");
