/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HealthCheckResponse = { assertions?: Array<string> | undefined };

export const HealthCheckResponse$zodSchema: z.ZodType<
  HealthCheckResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  assertions: z.array(z.string()).optional(),
});
