/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const HealthField$zodSchema = z.enum([
  "endpoint",
  "gateway",
]);

export type HealthField = z.infer<typeof HealthField$zodSchema>;
