/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const HealthField = {
  Endpoint: "endpoint",
  Gateway: "gateway",
} as const;
export type HealthField = ClosedEnum<typeof HealthField>;

export const HealthField$zodSchema = z.enum([
  "endpoint",
  "gateway",
]);
