/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A health check response
 */
export type HealthCheckLogResponse = {
  status?: number | undefined;
  body?: string | undefined;
  headers?: { [k: string]: string } | undefined;
};

export const HealthCheckLogResponse$zodSchema: z.ZodType<
  HealthCheckLogResponse
> = z.object({
  body: z.string().optional().describe("The response body"),
  headers: z.record(z.string(), z.string()).optional().describe(
    "The response headers",
  ),
  status: z.int().optional().describe("The response status"),
}).describe("A health check response");
