/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AnalyticsType, AnalyticsType$zodSchema } from "./analyticstype.js";

export type HistogramTimestamp = {
  from?: number | undefined;
  to?: number | undefined;
  interval?: number | undefined;
};

export const HistogramTimestamp$zodSchema: z.ZodType<HistogramTimestamp> = z
  .object({
    from: z.int().optional(),
    interval: z.int().optional(),
    to: z.int().optional(),
  });

export type Bucket = {
  name?: string | undefined;
  data?: Array<number> | undefined;
};

export const Bucket$zodSchema: z.ZodType<Bucket> = z.object({
  data: z.array(z.number()).optional(),
  name: z.string().optional(),
});

export type Value = {
  buckets?: Array<Bucket> | undefined;
  field?: string | undefined;
  name?: string | undefined;
  metadata?: { [k: string]: { [k: string]: string } } | undefined;
};

export const Value$zodSchema: z.ZodType<Value> = z.object({
  buckets: z.array(z.lazy(() => Bucket$zodSchema)).optional(),
  field: z.string().optional(),
  metadata: z.record(z.string(), z.record(z.string(), z.string())).optional(),
  name: z.string().optional(),
});

/**
 * Generic Analytics response
 */
export type HistogramAnalytics = {
  analyticsType: AnalyticsType;
  timestamp?: HistogramTimestamp | undefined;
  values?: Array<Value> | undefined;
};

export const HistogramAnalytics$zodSchema: z.ZodType<HistogramAnalytics> = z
  .object({
    analyticsType: AnalyticsType$zodSchema.describe(
      "The type of the analytics",
    ),
    timestamp: z.lazy(() => HistogramTimestamp$zodSchema).optional(),
    values: z.array(z.lazy(() => Value$zodSchema)).optional(),
  }).describe("Generic Analytics response");
