/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HttpHeader, HttpHeader$zodSchema } from "./httpheader.js";
import { KeyStore, KeyStore$zodSchema } from "./keystore.js";
import { TrustStore, TrustStore$zodSchema } from "./truststore.js";

export type HttpClientSslOptions = {
  trustAll?: boolean | undefined;
  hostnameVerifier?: boolean | undefined;
  trustStore?: TrustStore | undefined;
  keyStore?: KeyStore | undefined;
  headers?: Array<HttpHeader> | undefined;
};

export const HttpClientSslOptions$zodSchema: z.ZodType<HttpClientSslOptions> = z
  .object({
    headers: z.array(HttpHeader$zodSchema).optional(),
    hostnameVerifier: z.boolean().default(false).describe(
      "Should the hostname be verified or not",
    ),
    keyStore: KeyStore$zodSchema.optional(),
    trustAll: z.boolean().default(false).describe(
      "Trust all certificates or not",
    ),
    trustStore: TrustStore$zodSchema.optional(),
  });
