/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DynamicPropertyProvider,
  DynamicPropertyProvider$zodSchema,
} from "./dynamicpropertyprovider.js";
import { HttpHeader, HttpHeader$zodSchema } from "./httpheader.js";
import { HttpMethod, HttpMethod$zodSchema } from "./httpmethod.js";

export type HttpDynamicPropertyProviderConfiguration = {
  url?: string | undefined;
  specification?: string | undefined;
  useSystemProxy?: boolean | undefined;
  method?: HttpMethod | undefined;
  headers?: Array<HttpHeader> | undefined;
  body?: string | undefined;
  provider: DynamicPropertyProvider;
};

export const HttpDynamicPropertyProviderConfiguration$zodSchema: z.ZodType<
  HttpDynamicPropertyProviderConfiguration
> = z.object({
  body: z.string().optional().describe("The body of the request"),
  headers: z.array(HttpHeader$zodSchema).optional(),
  method: HttpMethod$zodSchema.optional().describe(
    "The method of the selector",
  ),
  provider: DynamicPropertyProvider$zodSchema.describe(
    "The type of the dynamic property provider.",
  ),
  specification: z.string().optional().describe(
    "The specification of the dynamic property provider",
  ),
  url: z.string().optional().describe(
    "The url of the dynamic property provider",
  ),
  useSystemProxy: z.boolean().default(false).describe(
    "Use the system proxy or not",
  ),
});
