/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Cors, Cors$zodSchema } from "./cors.js";
import { Entrypoint, Entrypoint$zodSchema } from "./entrypoint.js";
import { ListenerType, ListenerType$zodSchema } from "./listenertype.js";
import { PathV4, PathV4$zodSchema } from "./pathv4.js";

export type HttpListener = {
  type: ListenerType;
  entrypoints?: Array<Entrypoint> | undefined;
  servers?: Array<string> | undefined;
  paths?: Array<PathV4> | undefined;
  pathMappings?: Array<string> | undefined;
  cors?: Cors | undefined;
};

export const HttpListener$zodSchema: z.ZodType<
  HttpListener,
  z.ZodTypeDef,
  unknown
> = z.object({
  cors: Cors$zodSchema.optional(),
  entrypoints: z.array(Entrypoint$zodSchema).optional(),
  pathMappings: z.array(z.string()).optional(),
  paths: z.array(PathV4$zodSchema).optional(),
  servers: z.array(z.string()).optional(),
  type: ListenerType$zodSchema,
});
