/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ImportSwaggerDescriptor = {
  payload?: string | undefined;
  withDocumentation?: boolean | undefined;
  withOASValidationPolicy?: boolean | undefined;
  withPolicies?: Array<string> | undefined;
  withPolicyPaths?: boolean | undefined;
};

export const ImportSwaggerDescriptor$zodSchema: z.ZodType<
  ImportSwaggerDescriptor
> = z.object({
  payload: z.string().optional().describe("The Swagger/OpenAPI content."),
  withDocumentation: z.boolean().optional().describe(
    "Create documentation based on Swagger/OpenAPI specification.",
  ),
  withOASValidationPolicy: z.boolean().optional().describe(
    "Add an OpenAPI Specification validation policy based on OpenAPI specification.",
  ),
  withPolicies: z.array(z.string()).optional().describe(
    "Policy visitor IDs to apply during OpenAPI import.",
  ),
  withPolicyPaths: z.boolean().optional().describe(
    "Create a flow for each path declared in the OpenAPI specification.",
  ),
});
