/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Whether the payload is inline WSDL or a remote URL.
 */
export const ImportWsdlDescriptorType = {
  Inline: "INLINE",
  Url: "URL",
} as const;
/**
 * Whether the payload is inline WSDL or a remote URL.
 */
export type ImportWsdlDescriptorType = ClosedEnum<
  typeof ImportWsdlDescriptorType
>;

export const ImportWsdlDescriptorType$zodSchema = z.enum([
  "INLINE",
  "URL",
]).describe("Whether the payload is inline WSDL or a remote URL.");

export type ImportWsdlDescriptor = {
  payload: string;
  type?: ImportWsdlDescriptorType | undefined;
  withDocumentation?: boolean | undefined;
  withOASValidationPolicy?: boolean | undefined;
  withPolicies?: Array<string> | undefined;
};

export const ImportWsdlDescriptor$zodSchema: z.ZodType<ImportWsdlDescriptor> = z
  .object({
    payload: z.string().describe(
      "Inline WSDL content (when type is INLINE) or a remote URL (when type is URL).",
    ),
    type: ImportWsdlDescriptorType$zodSchema.default("INLINE").describe(
      "Whether the payload is inline WSDL or a remote URL.",
    ),
    withDocumentation: z.boolean().optional().describe(
      "Generate a Swagger documentation page from the converted OpenAPI spec.",
    ),
    withOASValidationPolicy: z.boolean().optional().describe(
      "Add an OAS Validation policy to every flow.",
    ),
    withPolicies: z.array(z.string()).optional().describe(
      "Policy visitor IDs to apply (e.g. rest-to-soap, json-validation, mock, validate-request, xml-validation).",
    ),
  });
