/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IngestedApi = {
  id?: string | undefined;
  name?: string | undefined;
};

export const IngestedApi$zodSchema: z.ZodType<
  IngestedApi,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});
