/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  IngestedApisResponseIngestedApisResponse,
  IngestedApisResponseIngestedApisResponse$zodSchema,
} from "./ingestedapisresponseingestedapisresponse.js";

export type IngestedApisRequest = {
  envId?: string | undefined;
  integrationId: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const IngestedApisRequest$zodSchema: z.ZodType<
  IngestedApisRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  integrationId: z.string().describe("Id of an integration."),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
});

export type IngestedApisResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  IngestedApisResponse?: IngestedApisResponseIngestedApisResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const IngestedApisResponse$zodSchema: z.ZodType<
  IngestedApisResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  IngestedApisResponse: IngestedApisResponseIngestedApisResponse$zodSchema
    .optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
