/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IngestedApi, IngestedApi$zodSchema } from "./ingestedapi.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of Ingested APIs
 */
export type IngestedApisResponse = {
  data?: Array<IngestedApi> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const IngestedApisResponse$zodSchema: z.ZodType<IngestedApisResponse> = z
  .object({
    data: z.array(IngestedApi$zodSchema).optional().describe(
      "List of Ingested APIs .",
    ),
    links: Links$zodSchema.optional().describe("List of links for pagination"),
    pagination: Pagination$zodSchema.optional().describe(
      "Generic object to handle pagination data.",
    ),
  }).describe("Page of Ingested APIs");
