/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IngestedApi, IngestedApi$zodSchema } from "./ingestedapi.js";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of Ingested APIs
 */
export type IngestedApisResponseIngestedApisResponse = {
  data?: Array<IngestedApi> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const IngestedApisResponseIngestedApisResponse$zodSchema: z.ZodType<
  IngestedApisResponseIngestedApisResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(IngestedApi$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of Ingested APIs");
