/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IntegrationWellKnownUrl = { url?: string | undefined };

export const IntegrationWellKnownUrl$zodSchema: z.ZodType<
  IntegrationWellKnownUrl
> = z.object({
  url: z.string().optional().describe("URL for well-known endpoint"),
});
