/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TrustStoreType, TrustStoreType$zodSchema } from "./truststoretype.js";

export type JKSTrustStore = {
  type: TrustStoreType;
  path?: string | undefined;
  content?: string | undefined;
  password?: string | undefined;
};

export const JKSTrustStore$zodSchema: z.ZodType<JKSTrustStore> = z.object({
  content: z.string().optional().describe("The content of the trust store"),
  password: z.string().optional().describe("The password of the trust store"),
  path: z.string().optional().describe("The path of the trust store"),
  type: TrustStoreType$zodSchema.describe("The type of the trust store."),
});
