/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Entrypoint, Entrypoint$zodSchema } from "./entrypoint.js";
import { ListenerType, ListenerType$zodSchema } from "./listenertype.js";

export type KafkaListener = {
  type: ListenerType;
  entrypoints?: Array<Entrypoint> | undefined;
  servers?: Array<string> | undefined;
  host: string;
  port?: number | undefined;
};

export const KafkaListener$zodSchema: z.ZodType<KafkaListener> = z.object({
  entrypoints: z.array(Entrypoint$zodSchema).optional(),
  host: z.string().describe(
    "A hostname for which the API will match against SNI.",
  ),
  port: z.int().optional().describe("The port of the listener"),
  servers: z.array(z.string()).optional(),
  type: ListenerType$zodSchema.describe("Listener type."),
});
