/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the key store.
 */
export const KeyStoreType$zodSchema = z.enum([
  "JKS",
  "PEM",
  "PKCS12",
  "NONE",
]).describe("The type of the key store.");

export type KeyStoreType = z.infer<typeof KeyStoreType$zodSchema>;
