/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * List of links for pagination
 */
export type Links = {
  self?: string | undefined;
  first?: string | undefined;
  last?: string | undefined;
  previous?: string | undefined;
  next?: string | undefined;
};

export const Links$zodSchema: z.ZodType<Links> = z.object({
  first: z.string().optional().describe(
    "In a paginated response, link to the first page",
  ),
  last: z.string().optional().describe(
    "In a paginated response, link to the last page",
  ),
  next: z.string().optional().describe(
    "In a paginated response, link to the next page. Maybe null if current is the last page",
  ),
  previous: z.string().optional().describe(
    "In a paginated response, link to the previous page. Maybe null if current is the first page",
  ),
  self: z.string().optional().describe("Link to current resource"),
}).describe("List of links for pagination");
