/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  MembersResponse,
  MembersResponse$zodSchema,
} from "./membersresponse.js";

export type ListApiMembersRequest = {
  envId?: string | undefined;
  apiId: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const ListApiMembersRequest$zodSchema: z.ZodType<ListApiMembersRequest> =
  z.object({
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
    page: z.int().default(1).describe("The page number for pagination."),
    perPage: z.int().default(10).describe(
      "The number of items per page for pagination.\n",
    ),
  });

export type ListApiMembersResponse = MembersResponse | ErrorT;

export const ListApiMembersResponse$zodSchema: z.ZodType<
  ListApiMembersResponse
> = z.union([
  MembersResponse$zodSchema,
  ErrorT$zodSchema,
]);
