/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Listener type.
 */
export const ListenerType$zodSchema = z.enum([
  "HTTP",
  "SUBSCRIPTION",
  "TCP",
  "KAFKA",
]).describe("Listener type.");

export type ListenerType = z.infer<typeof ListenerType$zodSchema>;
