/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { GroupsResponse, GroupsResponse$zodSchema } from "./groupsresponse.js";

export type ListGroupsRequest = {
  envId?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const ListGroupsRequest$zodSchema: z.ZodType<
  ListGroupsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
});

export type ListGroupsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  GroupsResponse?: GroupsResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const ListGroupsResponse$zodSchema: z.ZodType<
  ListGroupsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  GroupsResponse: GroupsResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
