/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AsyncJobsResponse,
  AsyncJobsResponse$zodSchema,
} from "./asyncjobsresponse.js";
import { AsyncJobStatus, AsyncJobStatus$zodSchema } from "./asyncjobstatus.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type ListAsyncJobRequest = {
  envId?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
  sourceId: string;
  status: AsyncJobStatus;
};

export const ListAsyncJobRequest$zodSchema: z.ZodType<
  ListAsyncJobRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
  sourceId: z.string().describe("SourceId to filter"),
  status: AsyncJobStatus$zodSchema,
});

export type ListAsyncJobResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  AsyncJobsResponse?: AsyncJobsResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const ListAsyncJobResponse$zodSchema: z.ZodType<
  ListAsyncJobResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  AsyncJobsResponse: AsyncJobsResponse$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
