/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  MembersResponse,
  MembersResponse$zodSchema,
} from "./membersresponse.js";

export type ListIntegrationMembersRequest = {
  envId?: string | undefined;
  integrationId: string;
  page?: number | undefined;
  perPage?: number | undefined;
};

export const ListIntegrationMembersRequest$zodSchema: z.ZodType<
  ListIntegrationMembersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  integrationId: z.string().describe("Id of an integration."),
  page: z.number().int().default(1).describe("The page number for pagination."),
  perPage: z.number().int().default(10).describe(
    "The number of items per page for pagination.\n"
      + "",
  ),
});

export type ListIntegrationMembersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  MembersResponse?: MembersResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const ListIntegrationMembersResponse$zodSchema: z.ZodType<
  ListIntegrationMembersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  MembersResponse: MembersResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
