/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LoggingPhase = {
  request?: boolean | undefined;
  response?: boolean | undefined;
};

export const LoggingPhase$zodSchema: z.ZodType<
  LoggingPhase,
  z.ZodTypeDef,
  unknown
> = z.object({
  request: z.boolean().optional(),
  response: z.boolean().optional(),
});
