/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LoggingContentV2,
  LoggingContentV2$zodSchema,
} from "./loggingcontentv2.js";
import { LoggingModeV2, LoggingModeV2$zodSchema } from "./loggingmodev2.js";
import { LoggingScope, LoggingScope$zodSchema } from "./loggingscope.js";

export type LoggingV2 = {
  mode?: LoggingModeV2 | undefined;
  scope?: LoggingScope | undefined;
  content?: LoggingContentV2 | undefined;
  condition?: string | undefined;
};

export const LoggingV2$zodSchema: z.ZodType<LoggingV2, z.ZodTypeDef, unknown> =
  z.object({
    condition: z.string().optional(),
    content: LoggingContentV2$zodSchema.optional(),
    mode: LoggingModeV2$zodSchema.optional(),
    scope: LoggingScope$zodSchema.optional(),
  });
