/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Selector type.
 */
export const McpSelectorType = {
  Http: "HTTP",
  Channel: "CHANNEL",
  Condition: "CONDITION",
  Mcp: "MCP",
} as const;
/**
 * Selector type.
 */
export type McpSelectorType = ClosedEnum<typeof McpSelectorType>;

export const McpSelectorType$zodSchema = z.enum([
  "HTTP",
  "CHANNEL",
  "CONDITION",
  "MCP",
]).describe("Selector type.");

export type McpSelector = { type: McpSelectorType; methods: Array<string> };

export const McpSelector$zodSchema: z.ZodType<McpSelector> = z.object({
  methods: z.array(z.string()).describe("MCP Methods to select on"),
  type: McpSelectorType$zodSchema.describe("Selector type."),
});
