/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Media = {
  id?: string | undefined;
  hash?: string | undefined;
  type?: string | undefined;
  subType?: string | undefined;
  fileName?: string | undefined;
  size?: number | undefined;
  data?: string | undefined;
  createdAt?: string | undefined;
};

export const Media$zodSchema: z.ZodType<Media> = z.object({
  createdAt: z.iso.datetime({ offset: true }).optional().describe(
    "Media's creation date.",
  ),
  data: z.string().optional().describe("Media's data."),
  fileName: z.string().optional().describe("Media's file name."),
  hash: z.string().optional().describe("Media's hash."),
  id: z.string().optional().describe("Media's uuid."),
  size: z.int().optional().describe("Media's size."),
  subType: z.string().optional().describe("Media's sub type."),
  type: z.string().optional().describe("Media's type."),
});
