/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Role, Role$zodSchema } from "./role.js";

export type Member = {
  id?: string | undefined;
  displayName?: string | undefined;
  roles?: Array<Role> | undefined;
};

export const Member$zodSchema: z.ZodType<Member> = z.object({
  displayName: z.string().optional().describe("Member's name."),
  id: z.string().optional().describe("Member's uuid."),
  roles: z.array(Role$zodSchema).optional().describe(
    "The list of roles for this Member.",
  ),
});
