/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of membership
 */
export const MembershipMemberType$zodSchema = z.enum([
  "USER",
  "GROUP",
]).describe("The type of membership");

export type MembershipMemberType = z.infer<
  typeof MembershipMemberType$zodSchema
>;
