/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Links, Links$zodSchema } from "./links.js";
import { Member, Member$zodSchema } from "./member.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import {
  ResponseMetadata,
  ResponseMetadata$zodSchema,
} from "./responsemetadata.js";

/**
 * Page of API members
 */
export type MembersResponse = {
  data?: Array<Member> | undefined;
  links?: Links | undefined;
  metadata?: ResponseMetadata | undefined;
  pagination?: Pagination | undefined;
};

export const MembersResponse$zodSchema: z.ZodType<
  MembersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Member$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  metadata: ResponseMetadata$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of API members");
