/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The operation that emitted the message
 */
export const MessageOperation = {
  Publish: "publish",
  Subscribe: "subscribe",
} as const;
/**
 * The operation that emitted the message
 */
export type MessageOperation = ClosedEnum<typeof MessageOperation>;

export const MessageOperation$zodSchema = z.enum([
  "publish",
  "subscribe",
]).describe("The operation that emitted the message");
