/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The format of the metadata.
 */
export const MetadataFormat = {
  String: "STRING",
  Numeric: "NUMERIC",
  Boolean: "BOOLEAN",
  Date: "DATE",
  Mail: "MAIL",
  Url: "URL",
} as const;
/**
 * The format of the metadata.
 */
export type MetadataFormat = ClosedEnum<typeof MetadataFormat>;

export const MetadataFormat$zodSchema = z.enum([
  "STRING",
  "NUMERIC",
  "BOOLEAN",
  "DATE",
  "MAIL",
  "URL",
]).describe("The format of the metadata.");
