/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The format of the metadata.
 */
export const MetadataFormat$zodSchema = z.enum([
  "STRING",
  "NUMERIC",
  "BOOLEAN",
  "DATE",
  "MAIL",
  "URL",
]).describe("The format of the metadata.");

export type MetadataFormat = z.infer<typeof MetadataFormat$zodSchema>;
