/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * * MIGRATED: API is migrated
 *
 * @remarks
 * * MIGRATABLE: DRY_RUN and can works
 * * CAN_BE_FORCED: if you force, we upgrade
 * * IMPOSSIBLE: we don’t know howto upgrade
 */
export const MigrationStateType = {
  Migrated: "MIGRATED",
  Migratable: "MIGRATABLE",
  CanBeForced: "CAN_BE_FORCED",
  Impossible: "IMPOSSIBLE",
} as const;
/**
 * * MIGRATED: API is migrated
 *
 * @remarks
 * * MIGRATABLE: DRY_RUN and can works
 * * CAN_BE_FORCED: if you force, we upgrade
 * * IMPOSSIBLE: we don’t know howto upgrade
 */
export type MigrationStateType = ClosedEnum<typeof MigrationStateType>;

export const MigrationStateType$zodSchema = z.enum([
  "MIGRATED",
  "MIGRATABLE",
  "CAN_BE_FORCED",
  "IMPOSSIBLE",
]).describe(
  "* MIGRATED: API is migrated\n* MIGRATABLE: DRY_RUN and can works\n* CAN_BE_FORCED: if you force, we upgrade\n* IMPOSSIBLE: we don’t know howto upgrade\n",
);
