/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Links, Links$zodSchema } from "./links.js";
import { NativeApiLog, NativeApiLog$zodSchema } from "./nativeapilog.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

/**
 * Page of native API connection logs.
 */
export type NativeApiLogsResponse = {
  data?: Array<NativeApiLog> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const NativeApiLogsResponse$zodSchema: z.ZodType<NativeApiLogsResponse> =
  z.object({
    data: z.array(NativeApiLog$zodSchema).optional(),
    links: Links$zodSchema.optional().describe("List of links for pagination"),
    pagination: Pagination$zodSchema.optional().describe(
      "Generic object to handle pagination data.",
    ),
  }).describe("Page of native API connection logs.");
