/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { KeyStoreType, KeyStoreType$zodSchema } from "./keystoretype.js";

export type NoneKeyStore = { type: KeyStoreType };

export const NoneKeyStore$zodSchema: z.ZodType<
  NoneKeyStore,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: KeyStoreType$zodSchema,
});
