/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the page.
 */
export const PageType$zodSchema = z.enum([
  "ASCIIDOC",
  "ASYNCAPI",
  "MARKDOWN",
  "MARKDOWN_TEMPLATE",
  "SWAGGER",
  "FOLDER",
  "LINK",
  "ROOT",
  "SYSTEM_FOLDER",
  "TRANSLATION",
]).describe("The type of the page.");

export type PageType = z.infer<typeof PageType$zodSchema>;
