/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Page source's configuration.
 */
export type PageSourceConfiguration = {};

export const PageSourceConfiguration$zodSchema: z.ZodType<
  PageSourceConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("Page source's configuration.");

export type PageSource = {
  type?: string | undefined;
  configuration?: PageSourceConfiguration | undefined;
};

export const PageSource$zodSchema: z.ZodType<
  PageSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  configuration: z.lazy(() => PageSourceConfiguration$zodSchema).optional(),
  type: z.string().optional(),
});
