/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PageMedia = {
  name?: string | undefined;
  hash?: string | undefined;
  attachedAt?: string | undefined;
};

export const PageMedia$zodSchema: z.ZodType<PageMedia> = z.object({
  attachedAt: z.iso.datetime({ offset: true }).optional().describe(
    "Media's attachment date.",
  ),
  hash: z.string().optional().describe("Media's hash."),
  name: z.string().optional().describe("Media's name."),
});
