/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Page source's configuration.
 */
export type PageSourceConfiguration = {};

export const PageSourceConfiguration$zodSchema: z.ZodType<
  PageSourceConfiguration
> = z.object({}).describe("Page source's configuration.");

export type PageSource = {
  type?: string | undefined;
  configuration?: PageSourceConfiguration | undefined;
};

export const PageSource$zodSchema: z.ZodType<PageSource> = z.object({
  configuration: z.lazy(() => PageSourceConfiguration$zodSchema).optional()
    .describe("Page source's configuration."),
  type: z.string().optional().describe(
    "The type of the page source (=fetcher type).",
  ),
});
