/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiV4Output, ApiV4Output$zodSchema } from "./apiv4output.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type PatchApiRequest = {
  envId?: string | undefined;
  apiId: string;
  dryRun?: boolean | undefined;
  RequestBody: { [k: string]: any };
};

export const PatchApiRequest$zodSchema: z.ZodType<PatchApiRequest> = z.object({
  RequestBody: z.record(z.string(), z.any()),
  apiId: z.string().describe("Id of an API."),
  dryRun: z.boolean().default(false),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type PatchApiResponse = ApiV4Output | ErrorT;

export const PatchApiResponse$zodSchema: z.ZodType<PatchApiResponse> = z.union([
  ApiV4Output$zodSchema,
  ErrorT$zodSchema,
]);
