/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { KeyStoreType, KeyStoreType$zodSchema } from "./keystoretype.js";

export type PEMKeyStore = {
  type: KeyStoreType;
  keyPath?: string | undefined;
  keyContent?: string | undefined;
  certPath?: string | undefined;
  certContent?: string | undefined;
};

export const PEMKeyStore$zodSchema: z.ZodType<
  PEMKeyStore,
  z.ZodTypeDef,
  unknown
> = z.object({
  certContent: z.string().optional(),
  certPath: z.string().optional(),
  keyContent: z.string().optional(),
  keyPath: z.string().optional(),
  type: KeyStoreType$zodSchema,
});
