/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Plan type.
 */
export const PlanType$zodSchema = z.enum([
  "API",
  "CATALOG",
]).describe("Plan type.");

export type PlanType = z.infer<typeof PlanType$zodSchema>;
