/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Plan validation type.
 */
export const PlanValidation$zodSchema = z.enum([
  "AUTO",
  "MANUAL",
]).describe("Plan validation type.");

export type PlanValidation = z.infer<typeof PlanValidation$zodSchema>;
