/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Plan validation type.
 */
export const PlanValidation = {
  Auto: "AUTO",
  Manual: "MANUAL",
} as const;
/**
 * Plan validation type.
 */
export type PlanValidation = ClosedEnum<typeof PlanValidation>;

export const PlanValidation$zodSchema = z.enum([
  "AUTO",
  "MANUAL",
]).describe("Plan validation type.");
