/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Links, Links$zodSchema } from "./links.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Plan, Plan$zodSchema } from "./plan.js";

/**
 * Page of API plans
 */
export type PlansResponse = {
  data?: Array<Plan> | undefined;
  pagination?: Pagination | undefined;
  links?: Links | undefined;
};

export const PlansResponse$zodSchema: z.ZodType<
  PlansResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Plan$zodSchema).optional(),
  links: Links$zodSchema.optional(),
  pagination: Pagination$zodSchema.optional(),
}).describe("Page of API plans");
