/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { FlowV2, FlowV2$zodSchema } from "./flowv2.js";
import { PlanMode, PlanMode$zodSchema } from "./planmode.js";
import { PlanSecurity, PlanSecurity$zodSchema } from "./plansecurity.js";
import { PlanStatus, PlanStatus$zodSchema } from "./planstatus.js";
import { PlanType, PlanType$zodSchema } from "./plantype.js";
import { PlanValidation, PlanValidation$zodSchema } from "./planvalidation.js";

export type PlanV2 = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  apiId?: string | undefined;
  apiProductId?: string | undefined;
  security?: PlanSecurity | undefined;
  mode?: PlanMode | undefined;
  characteristics?: Array<string> | undefined;
  closedAt?: string | undefined;
  commentMessage?: string | undefined;
  commentRequired?: boolean | undefined;
  createdAt?: string | undefined;
  crossId?: string | undefined;
  definitionVersion: DefinitionVersion;
  excludedGroups?: Array<string> | undefined;
  generalConditions?: string | undefined;
  order?: number | undefined;
  publishedAt?: string | undefined;
  selectionRule?: string | undefined;
  status?: PlanStatus | undefined;
  tags?: Array<string> | undefined;
  type?: PlanType | undefined;
  updatedAt?: string | undefined;
  validation?: PlanValidation | undefined;
  flows?: Array<FlowV2> | undefined;
};

export const PlanV2$zodSchema: z.ZodType<PlanV2> = z.object({
  apiId: z.string().optional().describe("Id of the API owning the plan."),
  apiProductId: z.string().optional().describe(
    "Id of the API Product owning the plan. Present only when the plan belongs to an API Product (omitted for API plans).",
  ),
  characteristics: z.array(z.string()).optional(),
  closedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the plan was closed.",
  ),
  commentMessage: z.string().optional().describe(
    "A message from the API Publisher that is displayed to the consumer at subscription time.",
  ),
  commentRequired: z.boolean().optional().describe(
    "A flag indicating if the consumer has to write a \"consumer message\" or if he/she can leave the field blank.",
  ),
  createdAt: z.iso.datetime({ offset: true }).optional().describe(
    "The last datetime when the plan was created.",
  ),
  crossId: z.string().optional().describe(
    "Plan's crossId. Identifies plan across environments.",
  ),
  definitionVersion: DefinitionVersion$zodSchema.describe(
    "API's gravitee definition version.",
  ),
  description: z.string().optional().describe(
    "Plan's description. A short description of your plan.",
  ),
  excludedGroups: z.array(z.string()).optional().describe(
    "Groups of users which are not allowed to subscribe to this plan.",
  ),
  flows: z.array(FlowV2$zodSchema).optional(),
  generalConditions: z.string().optional(),
  id: z.string().optional().describe("Plan's uuid."),
  mode: PlanMode$zodSchema.optional().describe(
    "The behavioural mode of the Plan (Standard for classical plan, Push for subscription plan).",
  ),
  name: z.string().optional().describe(
    "Plan's name. Duplicate names can exists.",
  ),
  order: z.int().optional(),
  publishedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The last datetime when the plan was published.",
  ),
  security: PlanSecurity$zodSchema.optional(),
  selectionRule: z.string().optional(),
  status: PlanStatus$zodSchema.optional().describe("Plan status."),
  tags: z.array(z.string()).optional().describe(
    "The list of sharding tags associated with this plan.",
  ),
  type: PlanType$zodSchema.optional().describe("Plan type."),
  updatedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The last datetime when the plan was updated.",
  ),
  validation: PlanValidation$zodSchema.optional().describe(
    "Plan validation type.",
  ),
});
