/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiSpecGenRequestState,
  ApiSpecGenRequestState$zodSchema,
} from "./apispecgenrequeststate.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type PostRequest = { envId?: string | undefined; apiId: string };

export const PostRequest$zodSchema: z.ZodType<PostRequest> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type PostResponse = ApiSpecGenRequestState | ErrorT;

export const PostResponse$zodSchema: z.ZodType<PostResponse> = z.union([
  ApiSpecGenRequestState$zodSchema,
  ErrorT$zodSchema,
]);
