/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  IngestionPreviewResponse,
  IngestionPreviewResponse$zodSchema,
} from "./ingestionpreviewresponse.js";

export type PreviewIntegrationRequest = {
  envId?: string | undefined;
  integrationId: string;
};

export const PreviewIntegrationRequest$zodSchema: z.ZodType<
  PreviewIntegrationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  integrationId: z.string().describe("Id of an integration."),
});

export type PreviewIntegrationResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  IngestionPreviewResponse?: IngestionPreviewResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const PreviewIntegrationResponse$zodSchema: z.ZodType<
  PreviewIntegrationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  IngestionPreviewResponse: IngestionPreviewResponse$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
