/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MembershipMemberType,
  MembershipMemberType$zodSchema,
} from "./membershipmembertype.js";

export type PrimaryOwner = {
  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  type?: MembershipMemberType | undefined;
};

export const PrimaryOwner$zodSchema: z.ZodType<
  PrimaryOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  displayName: z.string().optional(),
  email: z.string().optional(),
  id: z.string().optional(),
  type: MembershipMemberType$zodSchema.optional(),
});
