/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MembershipMemberType,
  MembershipMemberType$zodSchema,
} from "./membershipmembertype.js";

export type PrimaryOwner = {
  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  type?: MembershipMemberType | undefined;
};

export const PrimaryOwner$zodSchema: z.ZodType<PrimaryOwner> = z.object({
  displayName: z.string().optional().describe("Owner's name."),
  email: z.string().optional().describe(
    "Owner's email. Can be null if owner is a group.",
  ),
  id: z.string().optional().describe("Owner's uuid."),
  type: MembershipMemberType$zodSchema.optional().describe(
    "The type of membership",
  ),
});
