/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PromotionAuthor = {
  userId?: string | undefined;
  displayName?: string | undefined;
  email?: string | undefined;
  source?: string | undefined;
  sourceId?: string | undefined;
};

export const PromotionAuthor$zodSchema: z.ZodType<PromotionAuthor> = z.object({
  displayName: z.string().optional().describe(
    "The display name of the user who created the promotion.",
  ),
  email: z.string().optional().describe(
    "The email of the user who created the promotion.",
  ),
  source: z.string().optional().describe(
    "The source of the use who created the promotion.",
  ),
  sourceId: z.string().optional().describe(
    "The id of the user who created the promotion source.",
  ),
  userId: z.string().optional().describe("The user id."),
});
