/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PromotionRequest = {
  targetEnvCockpitId?: string | undefined;
  targetEnvName?: string | undefined;
};

export const PromotionRequest$zodSchema: z.ZodType<PromotionRequest> = z.object(
  {
    targetEnvCockpitId: z.string().optional().describe(
      "The target environment id where the promotion should be done.",
    ),
    targetEnvName: z.string().optional().describe(
      "The target environment name where the promotion should be done.",
    ),
  },
);
