/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Promotion, Promotion$zodSchema } from "./promotion.js";
import {
  PromotionRequest,
  PromotionRequest$zodSchema,
} from "./promotionrequest.js";

export type PromoteApiRequest = {
  envId?: string | undefined;
  apiId: string;
  PromotionRequest: PromotionRequest;
};

export const PromoteApiRequest$zodSchema: z.ZodType<PromoteApiRequest> = z
  .object({
    PromotionRequest: PromotionRequest$zodSchema,
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  });

export type PromoteApiResponse = Promotion | ErrorT;

export const PromoteApiResponse$zodSchema: z.ZodType<PromoteApiResponse> = z
  .union([
    Promotion$zodSchema,
    ErrorT$zodSchema,
  ]);
