/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PropertyOutput = {
  key: string;
  value: string;
  encrypted?: boolean | undefined;
  dynamic?: boolean | undefined;
};

export const PropertyOutput$zodSchema: z.ZodType<
  PropertyOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  dynamic: z.boolean().optional(),
  encrypted: z.boolean().optional(),
  key: z.string(),
  value: z.string(),
});
