/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RejectSubscription = { reason?: string | undefined };

export const RejectSubscription$zodSchema: z.ZodType<RejectSubscription> = z
  .object({
    reason: z.string().optional().describe(
      "Optional reason explaining why the subscription has been rejected.",
    ),
  });
