/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  RejectSubscription,
  RejectSubscription$zodSchema,
} from "./rejectsubscription.js";
import { Subscription, Subscription$zodSchema } from "./subscription.js";

export type RejectApiSubscriptionRequest = {
  envId?: string | undefined;
  apiId: string;
  subscriptionId: string;
  RejectSubscription: RejectSubscription;
};

export const RejectApiSubscriptionRequest$zodSchema: z.ZodType<
  RejectApiSubscriptionRequest
> = z.object({
  RejectSubscription: RejectSubscription$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  subscriptionId: z.string().describe("Id of a subscription."),
});

export type RejectApiSubscriptionResponse = Subscription | ErrorT;

export const RejectApiSubscriptionResponse$zodSchema: z.ZodType<
  RejectApiSubscriptionResponse
> = z.union([
  Subscription$zodSchema,
  ErrorT$zodSchema,
]);
