/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RejectSubscription = { reason?: string | undefined };

export const RejectSubscription$zodSchema: z.ZodType<
  RejectSubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  reason: z.string().optional(),
});
