/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { RenewApiKey, RenewApiKey$zodSchema } from "./renewapikey.js";

export type RenewApiSubscriptionApiKeysRequest = {
  envId?: string | undefined;
  apiId: string;
  subscriptionId: string;
  RenewApiKey: RenewApiKey;
};

export const RenewApiSubscriptionApiKeysRequest$zodSchema: z.ZodType<
  RenewApiSubscriptionApiKeysRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RenewApiKey: RenewApiKey$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  subscriptionId: z.string().describe("Id of a subscription."),
});

export type RenewApiSubscriptionApiKeysResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiKey?: ApiKey | undefined;
  ErrorT?: ErrorT | undefined;
};

export const RenewApiSubscriptionApiKeysResponse$zodSchema: z.ZodType<
  RenewApiSubscriptionApiKeysResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKey: ApiKey$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
