/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Generic object to handle additional information about an entity. Can also be used for pagination data.
 */
export type ResponseMetadata = {};

export const ResponseMetadata$zodSchema: z.ZodType<
  ResponseMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe(
  "Generic object to handle additional information about an entity. Can also be used for pagination data.",
);
