/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiReview, ApiReview$zodSchema } from "./apireview.js";

export type ReviewsAskRequest = {
  envId?: string | undefined;
  apiId: string;
  ApiReview: ApiReview;
};

export const ReviewsAskRequest$zodSchema: z.ZodType<ReviewsAskRequest> = z
  .object({
    ApiReview: ApiReview$zodSchema,
    apiId: z.string().describe("Id of an API."),
    envId: z.string().default("DEFAULT").describe(
      "Id or Hrid (Human readable Id) of an environment.",
    ),
  });
