/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Revision = {
  id?: string | undefined;
  revision?: number | undefined;
};

export const Revision$zodSchema: z.ZodType<Revision> = z.object({
  id: z.string().optional().describe(
    "Id of the page used to fill the content attributes.",
  ),
  revision: z.int().optional().describe("Revision number."),
});
