/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Scope of a role.
 */
export const RoleScope$zodSchema = z.enum([
  "API",
  "APPLICATION",
  "GROUP",
  "ENVIRONMENT",
  "ORGANIZATION",
  "PLATFORM",
  "INTEGRATION",
]).describe("Scope of a role.");

export type RoleScope = z.infer<typeof RoleScope$zodSchema>;
