/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the sampling
 */
export const SamplingType$zodSchema = z.enum([
  "PROBABILITY",
  "TEMPORAL",
  "COUNT",
]).describe("The type of the sampling");

export type SamplingType = z.infer<typeof SamplingType$zodSchema>;

export type Sampling = { type: SamplingType; value?: string | undefined };

export const Sampling$zodSchema: z.ZodType<Sampling, z.ZodTypeDef, unknown> = z
  .object({
    type: SamplingType$zodSchema,
    value: z.string().optional(),
  });
