/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChannelSelector,
  ChannelSelector$zodSchema,
} from "./channelselector.js";
import {
  ConditionSelector,
  ConditionSelector$zodSchema,
} from "./conditionselector.js";
import { HttpSelector, HttpSelector$zodSchema } from "./httpselector.js";
import { McpSelector, McpSelector$zodSchema } from "./mcpselector.js";

export type Selector =
  | ConditionSelector
  | McpSelector
  | HttpSelector
  | ChannelSelector;

export const Selector$zodSchema: z.ZodType<Selector> = z.union([
  ConditionSelector$zodSchema,
  McpSelector$zodSchema,
  HttpSelector$zodSchema,
  ChannelSelector$zodSchema,
]);
