/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The configuration of the service
 */
export type ServiceV4Configuration = {};

export const ServiceV4Configuration$zodSchema: z.ZodType<
  ServiceV4Configuration
> = z.object({}).describe("The configuration of the service");

export type ServiceV4 = {
  overrideConfiguration?: boolean | undefined;
  configuration?: ServiceV4Configuration | undefined;
  enabled?: boolean | undefined;
  type?: string | undefined;
};

export const ServiceV4$zodSchema: z.ZodType<ServiceV4> = z.object({
  configuration: z.lazy(() => ServiceV4Configuration$zodSchema).optional()
    .describe("The configuration of the service"),
  enabled: z.boolean().default(true).describe("Is the service enabled or not."),
  overrideConfiguration: z.boolean().default(false).describe(
    "Override the configuration of the service",
  ),
  type: z.string().optional(),
});
