/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * API SpecGen state value
 */
export const SpecGenState$zodSchema = z.enum([
  "AVAILABLE",
  "UNAVAILABLE",
  "STARTED",
  "GENERATING",
]).describe("API SpecGen state value");

export type SpecGenState = z.infer<typeof SpecGenState$zodSchema>;
