/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * API SpecGen state value
 */
export const SpecGenState = {
  Available: "AVAILABLE",
  Unavailable: "UNAVAILABLE",
  Started: "STARTED",
  Generating: "GENERATING",
} as const;
/**
 * API SpecGen state value
 */
export type SpecGenState = ClosedEnum<typeof SpecGenState>;

export const SpecGenState$zodSchema = z.enum([
  "AVAILABLE",
  "UNAVAILABLE",
  "STARTED",
  "GENERATING",
]).describe("API SpecGen state value");
