/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The configuration of the step
 */
export type StepV4Configuration = {};

export const StepV4Configuration$zodSchema: z.ZodType<StepV4Configuration> = z
  .object({}).describe("The configuration of the step");

export type StepV4 = {
  name?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  policy?: string | undefined;
  configuration?: StepV4Configuration | undefined;
  condition?: string | undefined;
  messageCondition?: string | undefined;
};

export const StepV4$zodSchema: z.ZodType<StepV4> = z.object({
  condition: z.string().optional().describe("The condition of the step"),
  configuration: z.lazy(() => StepV4Configuration$zodSchema).optional()
    .describe("The configuration of the step"),
  description: z.string().optional().describe("The description of the step"),
  enabled: z.boolean().default(true).describe("Is the step enabled or not."),
  messageCondition: z.string().optional().describe(
    "The message condition of the step",
  ),
  name: z.string().optional().describe("The name of the step"),
  policy: z.string().optional().describe("The policy of the step"),
});
