/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the subscription manageable by the api consumer.
 */
export const SubscriptionConsumerStatus$zodSchema = z.enum([
  "STARTED",
  "STOPPED",
  "FAILURE",
]).describe("The status of the subscription manageable by the api consumer.");

export type SubscriptionConsumerStatus = z.infer<
  typeof SubscriptionConsumerStatus$zodSchema
>;
