/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of the subscription manageable by the api publisher.
 */
export const SubscriptionStatus = {
  Pending: "PENDING",
  Rejected: "REJECTED",
  Accepted: "ACCEPTED",
  Closed: "CLOSED",
  Paused: "PAUSED",
  Resumed: "RESUMED",
} as const;
/**
 * The status of the subscription manageable by the api publisher.
 */
export type SubscriptionStatus = ClosedEnum<typeof SubscriptionStatus>;

export const SubscriptionStatus$zodSchema = z.enum([
  "PENDING",
  "REJECTED",
  "ACCEPTED",
  "CLOSED",
  "PAUSED",
  "RESUMED",
]).describe("The status of the subscription manageable by the api publisher.");
