/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BaseApi, BaseApi$zodSchema } from "./baseapi.js";
import { BaseApiProduct, BaseApiProduct$zodSchema } from "./baseapiproduct.js";
import {
  BaseApplication,
  BaseApplication$zodSchema,
} from "./baseapplication.js";
import { BasePlan, BasePlan$zodSchema } from "./baseplan.js";
import { BaseUser, BaseUser$zodSchema } from "./baseuser.js";
import {
  SubscriptionConsumerConfiguration,
  SubscriptionConsumerConfiguration$zodSchema,
} from "./subscriptionconsumerconfiguration.js";
import {
  SubscriptionConsumerStatus,
  SubscriptionConsumerStatus$zodSchema,
} from "./subscriptionconsumerstatus.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

/**
 * The origin of the subscription.
 */
export const SubscriptionOrigin = {
  Kubernetes: "KUBERNETES",
  Management: "MANAGEMENT",
} as const;
/**
 * The origin of the subscription.
 */
export type SubscriptionOrigin = ClosedEnum<typeof SubscriptionOrigin>;

export const SubscriptionOrigin$zodSchema = z.enum([
  "KUBERNETES",
  "MANAGEMENT",
]).describe("The origin of the subscription.");

export type Subscription = {
  id?: string | undefined;
  api?: BaseApi | undefined;
  apiProduct?: BaseApiProduct | undefined;
  plan?: BasePlan | undefined;
  application?: BaseApplication | undefined;
  consumerMessage?: string | undefined;
  publisherMessage?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  daysToExpirationOnLastNotification?: number | undefined;
  consumerConfiguration?: SubscriptionConsumerConfiguration | undefined;
  failureCause?: string | undefined;
  status?: SubscriptionStatus | undefined;
  consumerStatus?: SubscriptionConsumerStatus | undefined;
  processedBy?: BaseUser | undefined;
  subscribedBy?: BaseUser | undefined;
  processedAt?: string | undefined;
  startingAt?: string | undefined;
  endingAt?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  closedAt?: string | undefined;
  pausedAt?: string | undefined;
  consumerPausedAt?: string | undefined;
  origin?: SubscriptionOrigin | undefined;
};

export const Subscription$zodSchema: z.ZodType<Subscription> = z.object({
  api: BaseApi$zodSchema.optional(),
  apiProduct: BaseApiProduct$zodSchema.optional(),
  application: BaseApplication$zodSchema.optional(),
  closedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription was closed.",
  ),
  consumerConfiguration: SubscriptionConsumerConfiguration$zodSchema.optional()
    .describe(
      "Consumer configuration associated to the subscription in case it is attached to a push plan.",
    ),
  consumerMessage: z.string().optional().describe(
    "Message given by the api consumer when subscribing to the api.",
  ),
  consumerPausedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription was paused by the api consumer.",
  ),
  consumerStatus: SubscriptionConsumerStatus$zodSchema.optional().describe(
    "The status of the subscription manageable by the api consumer.",
  ),
  createdAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription was created.",
  ),
  daysToExpirationOnLastNotification: z.int().optional().describe(
    "Number of days before the expiration of this subscription when the last pre-expiration notification was sent.",
  ),
  endingAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription ends. No ending date means the subscription never ends.",
  ),
  failureCause: z.string().optional().describe(
    "Details about the last failure encountered on this subscription.",
  ),
  id: z.string().optional().describe("Subscription's uuid."),
  metadata: z.record(z.string(), z.string()).optional().describe(
    "A list of metadata associated to this subscription.",
  ),
  origin: SubscriptionOrigin$zodSchema.optional().describe(
    "The origin of the subscription.",
  ),
  pausedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription was paused by the api publisher.",
  ),
  plan: BasePlan$zodSchema.optional(),
  processedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription was processed.",
  ),
  processedBy: BaseUser$zodSchema.optional().describe(
    "Base information about a user.",
  ),
  publisherMessage: z.string().optional().describe(
    "Message given by the api publisher when accepting or rejecting the subscription.",
  ),
  startingAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the subscription starts. No starting date means the subscription starts immediately.",
  ),
  status: SubscriptionStatus$zodSchema.optional().describe(
    "The status of the subscription manageable by the api publisher.",
  ),
  subscribedBy: BaseUser$zodSchema.optional().describe(
    "Base information about a user.",
  ),
  updatedAt: z.iso.datetime({ offset: true }).optional().describe(
    "The last datetime when the subscription was updated.",
  ),
});
