/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Entrypoint, Entrypoint$zodSchema } from "./entrypoint.js";
import { ListenerType, ListenerType$zodSchema } from "./listenertype.js";

export type TcpListener = {
  type: ListenerType;
  entrypoints?: Array<Entrypoint> | undefined;
  servers?: Array<string> | undefined;
  hosts: Array<string>;
};

export const TcpListener$zodSchema: z.ZodType<
  TcpListener,
  z.ZodTypeDef,
  unknown
> = z.object({
  entrypoints: z.array(Entrypoint$zodSchema).optional(),
  hosts: z.array(z.string()),
  servers: z.array(z.string()).optional(),
  type: ListenerType$zodSchema,
});
