/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TracingMaskingStrategy,
  TracingMaskingStrategy$zodSchema,
} from "./tracingmaskingstrategy.js";

export type TracingRedactionRule = {
  attributeNamePattern: string;
  maskingStrategy?: TracingMaskingStrategy | undefined;
  valuePattern?: string | undefined;
};

export const TracingRedactionRule$zodSchema: z.ZodType<TracingRedactionRule> = z
  .object({
    attributeNamePattern: z.string().describe(
      "Glob pattern, short name (no dots — matches anywhere in key hierarchy), or regex:-prefixed Java regex matching the span attribute key.\n",
    ),
    maskingStrategy: TracingMaskingStrategy$zodSchema.optional(),
    valuePattern: z.string().optional().describe(
      "Optional Java regex (partial match). Rule only fires when the attribute value matches.\n",
    ),
  });
