/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiTransferOwnership,
  ApiTransferOwnership$zodSchema,
} from "./apitransferownership.js";

export type TransferOwnershipRequest = {
  envId?: string | undefined;
  apiId: string;
  ApiTransferOwnership: ApiTransferOwnership;
};

export const TransferOwnershipRequest$zodSchema: z.ZodType<
  TransferOwnershipRequest
> = z.object({
  ApiTransferOwnership: ApiTransferOwnership$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});
