/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiTransferOwnership,
  ApiTransferOwnership$zodSchema,
} from "./apitransferownership.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type TransferOwnershipRequest = {
  envId?: string | undefined;
  apiId: string;
  ApiTransferOwnership: ApiTransferOwnership;
};

export const TransferOwnershipRequest$zodSchema: z.ZodType<
  TransferOwnershipRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiTransferOwnership: ApiTransferOwnership$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type TransferOwnershipResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ErrorT?: ErrorT | undefined;
};

export const TransferOwnershipResponse$zodSchema: z.ZodType<
  TransferOwnershipResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
