/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiScoringTriggerResponse,
  ApiScoringTriggerResponse$zodSchema,
} from "./apiscoringtriggerresponse.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

export type TriggerApiScoringRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const TriggerApiScoringRequest$zodSchema: z.ZodType<
  TriggerApiScoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type TriggerApiScoringResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiScoringTriggerResponse?: ApiScoringTriggerResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const TriggerApiScoringResponse$zodSchema: z.ZodType<
  TriggerApiScoringResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiScoringTriggerResponse: ApiScoringTriggerResponse$zodSchema.optional(),
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
