/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of the trust store.
 */
export const TrustStoreType = {
  Jks: "JKS",
  Pem: "PEM",
  Pkcs12: "PKCS12",
  None: "NONE",
} as const;
/**
 * The type of the trust store.
 */
export type TrustStoreType = ClosedEnum<typeof TrustStoreType>;

export const TrustStoreType$zodSchema = z.enum([
  "JKS",
  "PEM",
  "PKCS12",
  "NONE",
]).describe("The type of the trust store.");
