/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { Page, Page$zodSchema } from "./page.js";

export type UnpublishDocumentationPageRequest = {
  envId?: string | undefined;
  apiId: string;
  pageId: string;
};

export const UnpublishDocumentationPageRequest$zodSchema: z.ZodType<
  UnpublishDocumentationPageRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  pageId: z.string().describe("Id of a documentation page."),
});

export type UnpublishDocumentationPageResponse = Page | ErrorT;

export const UnpublishDocumentationPageResponse$zodSchema: z.ZodType<
  UnpublishDocumentationPageResponse
> = z.union([
  Page$zodSchema,
  ErrorT$zodSchema,
]);
