/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateApiKey = { expireAt?: string | undefined };

export const UpdateApiKey$zodSchema: z.ZodType<UpdateApiKey> = z.object({
  expireAt: z.iso.datetime({ offset: true }).optional().describe(
    "The datetime when the API Key expires. No date means no expiration.",
  ),
});
