/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiV4Output, ApiV4Output$zodSchema } from "./apiv4output.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  ImportSwaggerDescriptor,
  ImportSwaggerDescriptor$zodSchema,
} from "./importswaggerdescriptor.js";

export type UpdateApiFromSwaggerRequest = {
  envId?: string | undefined;
  apiId: string;
  ImportSwaggerDescriptor: ImportSwaggerDescriptor;
};

export const UpdateApiFromSwaggerRequest$zodSchema: z.ZodType<
  UpdateApiFromSwaggerRequest
> = z.object({
  ImportSwaggerDescriptor: ImportSwaggerDescriptor$zodSchema,
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type UpdateApiFromSwaggerResponse = ApiV4Output | ErrorT;

export const UpdateApiFromSwaggerResponse$zodSchema: z.ZodType<
  UpdateApiFromSwaggerResponse
> = z.union([
  ApiV4Output$zodSchema,
  ErrorT$zodSchema,
]);
