/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiLifecycleState,
  ApiLifecycleState$zodSchema,
} from "./apilifecyclestate.js";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { Property, Property$zodSchema } from "./property.js";
import { Resource, Resource$zodSchema } from "./resource.js";
import {
  ResponseTemplate,
  ResponseTemplate$zodSchema,
} from "./responsetemplate.js";
import { Visibility, Visibility$zodSchema } from "./visibility.js";

export type UpdateApiFederated = {
  name: string;
  apiVersion: string;
  description?: string | undefined;
  definitionVersion: DefinitionVersion;
  groups?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  resources?: Array<Resource> | undefined;
  responseTemplates?:
    | { [k: string]: { [k: string]: ResponseTemplate } }
    | undefined;
  visibility?: Visibility | undefined;
  categories?: Array<string> | undefined;
  labels?: Array<string> | undefined;
  lifecycleState?: ApiLifecycleState | undefined;
  disableMembershipNotifications?: boolean | undefined;
  properties?: Array<Property> | undefined;
};

export const UpdateApiFederated$zodSchema: z.ZodType<
  UpdateApiFederated,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiVersion: z.string(),
  categories: z.array(z.string()).optional(),
  definitionVersion: DefinitionVersion$zodSchema,
  description: z.string().optional(),
  disableMembershipNotifications: z.boolean().default(false),
  groups: z.array(z.string()).optional(),
  labels: z.array(z.string()).optional(),
  lifecycleState: ApiLifecycleState$zodSchema.optional(),
  name: z.string(),
  properties: z.array(Property$zodSchema).optional(),
  resources: z.array(Resource$zodSchema).optional(),
  responseTemplates: z.record(z.record(ResponseTemplate$zodSchema)).optional(),
  tags: z.array(z.string()).optional(),
  visibility: Visibility$zodSchema.optional(),
});
