/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Update an API within a Category
 */
export type UpdateCategoryApi = { order: number };

export const UpdateCategoryApi$zodSchema: z.ZodType<
  UpdateCategoryApi,
  z.ZodTypeDef,
  unknown
> = z.object({
  order: z.number(),
}).describe("Update an API within a Category");
