/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiLifecycleState,
  ApiLifecycleState$zodSchema,
} from "./apilifecyclestate.js";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { Property, Property$zodSchema } from "./property.js";
import { Resource, Resource$zodSchema } from "./resource.js";
import {
  ResponseTemplate,
  ResponseTemplate$zodSchema,
} from "./responsetemplate.js";
import { Visibility, Visibility$zodSchema } from "./visibility.js";

export type UpdateApiFederated = {
  name: string;
  apiVersion: string;
  description?: string | undefined;
  definitionVersion: DefinitionVersion;
  groups?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  resources?: Array<Resource> | undefined;
  responseTemplates?:
    | { [k: string]: { [k: string]: ResponseTemplate } }
    | undefined;
  visibility?: Visibility | undefined;
  categories?: Array<string> | undefined;
  labels?: Array<string> | undefined;
  lifecycleState?: ApiLifecycleState | undefined;
  disableMembershipNotifications?: boolean | undefined;
  properties?: Array<Property> | undefined;
};

export const UpdateApiFederated$zodSchema: z.ZodType<UpdateApiFederated> = z
  .object({
    apiVersion: z.string().describe(
      "API's version. It's a simple string only used in the portal.",
    ),
    categories: z.array(z.string()).optional().describe(
      "The list of category ids or keys associated with this API.",
    ),
    definitionVersion: DefinitionVersion$zodSchema.describe(
      "API's gravitee definition version.",
    ),
    description: z.string().optional().describe(
      "API's description. A short description of your API.",
    ),
    disableMembershipNotifications: z.boolean().default(false).describe(
      "Disable membership notifications.",
    ),
    groups: z.array(z.string()).optional().describe(
      "List of group IDs associated with this API. Used to manage team access.",
    ),
    labels: z.array(z.string()).optional().describe(
      "The free list of labels associated with this API.",
    ),
    lifecycleState: ApiLifecycleState$zodSchema.optional().describe(
      "The status of the API regarding the console.",
    ),
    name: z.string().describe("API's name. Duplicate names can exists."),
    properties: z.array(Property$zodSchema).optional(),
    resources: z.array(Resource$zodSchema).optional(),
    responseTemplates: z.record(
      z.string(),
      z.record(z.string(), ResponseTemplate$zodSchema),
    ).optional(),
    tags: z.array(z.string()).optional().describe(
      "The list of sharding tags associated with this API.",
    ),
    visibility: Visibility$zodSchema.default("PRIVATE").describe(
      "The visibility of the resource regarding the portal.",
    ),
  });
