/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { FlowV2, FlowV2$zodSchema } from "./flowv2.js";
import { PlanValidation, PlanValidation$zodSchema } from "./planvalidation.js";
import { Rule2, Rule2$zodSchema } from "./rule2.js";

export type UpdatePlanV2Configuration = {};

export const UpdatePlanV2Configuration$zodSchema: z.ZodType<
  UpdatePlanV2Configuration,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type UpdatePlanV2Security = {
  configuration?: UpdatePlanV2Configuration | undefined;
};

export const UpdatePlanV2Security$zodSchema: z.ZodType<
  UpdatePlanV2Security,
  z.ZodTypeDef,
  unknown
> = z.object({
  configuration: z.lazy(() => UpdatePlanV2Configuration$zodSchema).optional(),
});

export type UpdatePlanV2 = {
  crossId?: string | undefined;
  characteristics?: Array<string> | undefined;
  commentMessage?: string | undefined;
  commentRequired?: boolean | undefined;
  definitionVersion: DefinitionVersion;
  description?: string | undefined;
  excludedGroups?: Array<string> | undefined;
  generalConditions?: string | undefined;
  name?: string | undefined;
  order?: number | undefined;
  security?: UpdatePlanV2Security | undefined;
  validation?: PlanValidation | undefined;
  selectionRule?: string | undefined;
  tags?: Array<string> | undefined;
  flows?: Array<FlowV2> | undefined;
  paths?: { [k: string]: Array<Rule2> } | undefined;
};

export const UpdatePlanV2$zodSchema: z.ZodType<
  UpdatePlanV2,
  z.ZodTypeDef,
  unknown
> = z.object({
  characteristics: z.array(z.string()).optional(),
  commentMessage: z.string().optional(),
  commentRequired: z.boolean().optional(),
  crossId: z.string().optional(),
  definitionVersion: DefinitionVersion$zodSchema,
  description: z.string().optional(),
  excludedGroups: z.array(z.string()).optional(),
  flows: z.array(FlowV2$zodSchema).optional(),
  generalConditions: z.string().optional(),
  name: z.string().optional(),
  order: z.number().int().optional(),
  paths: z.record(z.array(Rule2$zodSchema)).optional(),
  security: z.lazy(() => UpdatePlanV2Security$zodSchema).optional(),
  selectionRule: z.string().optional(),
  tags: z.array(z.string()).optional(),
  validation: PlanValidation$zodSchema.optional(),
});
