/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateMember = { roleName: string };

export const UpdateMember$zodSchema: z.ZodType<
  UpdateMember,
  z.ZodTypeDef,
  unknown
> = z.object({
  roleName: z.string(),
});
