/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import { UpdateApiKey, UpdateApiKey$zodSchema } from "./updateapikey.js";

export type UpdateApiSubscriptionApiKeyRequest = {
  envId?: string | undefined;
  apiId: string;
  subscriptionId: string;
  apiKeyId: string;
  UpdateApiKey: UpdateApiKey;
};

export const UpdateApiSubscriptionApiKeyRequest$zodSchema: z.ZodType<
  UpdateApiSubscriptionApiKeyRequest
> = z.object({
  UpdateApiKey: UpdateApiKey$zodSchema,
  apiId: z.string().describe("Id of an API."),
  apiKeyId: z.string().describe("Id of an API Key."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
  subscriptionId: z.string().describe("Id of a subscription."),
});

export type UpdateApiSubscriptionApiKeyResponse = ApiKey | ErrorT;

export const UpdateApiSubscriptionApiKeyResponse$zodSchema: z.ZodType<
  UpdateApiSubscriptionApiKeyResponse
> = z.union([
  ApiKey$zodSchema,
  ErrorT$zodSchema,
]);
