/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiLifecycleState,
  ApiLifecycleState$zodSchema,
} from "./apilifecyclestate.js";
import { ApiServicesV2, ApiServicesV2$zodSchema } from "./apiservicesv2.js";
import {
  DefinitionVersion,
  DefinitionVersion$zodSchema,
} from "./definitionversion.js";
import { ExecutionMode, ExecutionMode$zodSchema } from "./executionmode.js";
import { FlowMode, FlowMode$zodSchema } from "./flowmode.js";
import { FlowV2, FlowV2$zodSchema } from "./flowv2.js";
import { Property, Property$zodSchema } from "./property.js";
import { Proxy, Proxy$zodSchema } from "./proxy.js";
import { Resource, Resource$zodSchema } from "./resource.js";
import {
  ResponseTemplate,
  ResponseTemplate$zodSchema,
} from "./responsetemplate.js";
import { Visibility, Visibility$zodSchema } from "./visibility.js";

export type UpdateApiV2 = {
  name: string;
  apiVersion: string;
  description?: string | undefined;
  definitionVersion: DefinitionVersion;
  groups?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  resources?: Array<Resource> | undefined;
  responseTemplates?:
    | { [k: string]: { [k: string]: ResponseTemplate } }
    | undefined;
  visibility?: Visibility | undefined;
  categories?: Array<string> | undefined;
  labels?: Array<string> | undefined;
  lifecycleState?: ApiLifecycleState | undefined;
  disableMembershipNotifications?: boolean | undefined;
  properties?: Array<Property> | undefined;
  proxy?: Proxy | undefined;
  flowMode?: FlowMode | undefined;
  flows?: Array<FlowV2> | undefined;
  services?: ApiServicesV2 | undefined;
  pathMappings?: Array<string> | undefined;
  executionMode?: ExecutionMode | undefined;
};

export const UpdateApiV2$zodSchema: z.ZodType<UpdateApiV2> = z.object({
  apiVersion: z.string().describe(
    "API's version. It's a simple string only used in the portal.",
  ),
  categories: z.array(z.string()).optional().describe(
    "The list of category ids or keys associated with this API.",
  ),
  definitionVersion: DefinitionVersion$zodSchema.describe(
    "API's gravitee definition version.",
  ),
  description: z.string().optional().describe(
    "API's description. A short description of your API.",
  ),
  disableMembershipNotifications: z.boolean().default(false).describe(
    "Disable membership notifications.",
  ),
  executionMode: ExecutionMode$zodSchema.default("V4_EMULATION_ENGINE")
    .describe("The execution mode of the API."),
  flowMode: FlowMode$zodSchema.default("DEFAULT").describe("API's flow mode."),
  flows: z.array(FlowV2$zodSchema).optional().describe(
    "The list of flows associated with this API.",
  ),
  groups: z.array(z.string()).optional().describe(
    "List of group IDs associated with this API. Used to manage team access.",
  ),
  labels: z.array(z.string()).optional().describe(
    "The free list of labels associated with this API.",
  ),
  lifecycleState: ApiLifecycleState$zodSchema.optional().describe(
    "The status of the API regarding the console.",
  ),
  name: z.string().describe("API's name. Duplicate names can exists."),
  pathMappings: z.array(z.string()).optional().describe(
    "The list of path mappings associated with this API.",
  ),
  properties: z.array(Property$zodSchema).optional(),
  proxy: Proxy$zodSchema.optional(),
  resources: z.array(Resource$zodSchema).optional(),
  responseTemplates: z.record(
    z.string(),
    z.record(z.string(), ResponseTemplate$zodSchema),
  ).optional(),
  services: ApiServicesV2$zodSchema.optional(),
  tags: z.array(z.string()).optional().describe(
    "The list of sharding tags associated with this API.",
  ),
  visibility: Visibility$zodSchema.default("PRIVATE").describe(
    "The visibility of the resource regarding the portal.",
  ),
});
