/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  VerifyApiDeploymentResponse,
  VerifyApiDeploymentResponse$zodSchema,
} from "./verifyapideploymentresponse.js";

export type VerifyApiDeploymentRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const VerifyApiDeploymentRequest$zodSchema: z.ZodType<
  VerifyApiDeploymentRequest
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type VerifyApiDeploymentResponseResponse =
  | VerifyApiDeploymentResponse
  | ErrorT;

export const VerifyApiDeploymentResponseResponse$zodSchema: z.ZodType<
  VerifyApiDeploymentResponseResponse
> = z.union([
  VerifyApiDeploymentResponse$zodSchema,
  ErrorT$zodSchema,
]);
