/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VerifyApiDeploymentResponse = {
  ok?: boolean | undefined;
  reason?: string | undefined;
};

export const VerifyApiDeploymentResponse$zodSchema: z.ZodType<
  VerifyApiDeploymentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ok: z.boolean().optional(),
  reason: z.string().optional(),
});
