/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";
import {
  VerifyApiDeploymentResponse,
  VerifyApiDeploymentResponse$zodSchema,
} from "./verifyapideploymentresponse.js";

export type VerifyApiDeploymentRequest = {
  envId?: string | undefined;
  apiId: string;
};

export const VerifyApiDeploymentRequest$zodSchema: z.ZodType<
  VerifyApiDeploymentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().describe("Id of an API."),
  envId: z.string().default("DEFAULT").describe(
    "Id or Hrid (Human readable Id) of an environment.",
  ),
});

export type VerifyApiDeploymentResponseResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  VerifyApiDeploymentResponse?: VerifyApiDeploymentResponse | undefined;
  ErrorT?: ErrorT | undefined;
};

export const VerifyApiDeploymentResponseResponse$zodSchema: z.ZodType<
  VerifyApiDeploymentResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ErrorT: ErrorT$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  VerifyApiDeploymentResponse: VerifyApiDeploymentResponse$zodSchema.optional(),
});
