/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Path, Path$zodSchema } from "./path.js";

export type VerifyApiPaths = { apiId?: string | undefined; paths: Array<Path> };

export const VerifyApiPaths$zodSchema: z.ZodType<
  VerifyApiPaths,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiId: z.string().optional(),
  paths: z.array(Path$zodSchema),
});
