/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Result of the API hosts verification
 */
export type VerifyApiHostsResponse = {
  ok?: boolean | undefined;
  reason?: string | undefined;
};

export const VerifyApiHostsResponse$zodSchema: z.ZodType<
  VerifyApiHostsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ok: z.boolean().optional(),
  reason: z.string().optional(),
}).describe("Result of the API hosts verification");
