/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VerifySubscription = { applicationId: string; apiKey: string };

export const VerifySubscription$zodSchema: z.ZodType<
  VerifySubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKey: z.string(),
  applicationId: z.string(),
});
