/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The visibility of the resource regarding the portal.
 */
export const Visibility$zodSchema = z.enum([
  "PUBLIC",
  "PRIVATE",
]).describe("The visibility of the resource regarding the portal.");

export type Visibility = z.infer<typeof Visibility$zodSchema>;
